"""CUSMA multi-party trade negotiation — full MARL demo with real LLMs.

Three country workflows (USA, Canada, Mexico) negotiate terms of a CUSMA/USMCA
trade agreement over multiple rounds inside an
:class:`~choreo_mini.core.episode.Episode`.  Every proposal is generated by a
real OpenAI LLM; the episode runs until either all parties signal
``READY_TO_STOP: YES`` (each for asymmetric reasons) or ``max_rounds`` is
reached (triggering a deadlock outcome).

Prerequisites
-------------
Set your OpenAI API key as an environment variable — never hardcode it::

    export OPENAI_API_KEY=sk-proj-...

Then run::

    python examples/cusma_negotiation.py

Optional env vars::

    CUSMA_MODEL=gpt-4o-mini     # model to use (default: gpt-4o-mini)
    CUSMA_MAX_ROUNDS=8          # max negotiation rounds (default: 8)

Output is written to output/cusma_trace.ndjson.

Architecture
------------
::

    Episode (max_rounds)
    ├── USAWorkflow      → AgentNode("USANegotiator",    llm=gpt-4o-mini)
    ├── CanadaWorkflow   → AgentNode("CanadaNegotiator", llm=gpt-4o-mini)
    └── MexicoWorkflow   → AgentNode("MexicoNegotiator", llm=gpt-4o-mini)

Each round:
  1. Every country reads the current env_state (others' last proposals).
  2. Each negotiator produces a dual-format proposal — a negotiating position
     at the table AND domestic policy measures taken unilaterally.
  3. Each party self-reports READY_TO_STOP: YES/NO at the end of its proposal.
  4. The episode ends when ALL parties signal YES (for different reasons).
  5. If max_rounds is exhausted first, a deadlock outcome is reported with
     Article 34.7 annual-review and 6-month withdrawal-notice implications.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

project_root = Path(__file__).resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from choreo_mini.core.episode import Episode
from choreo_mini.core.llm import LLM, CustomLLM
from choreo_mini.core.nodes import AgentNode
from choreo_mini.core.observability import CompositeHook, JsonFileHook, StdoutHook
from choreo_mini.core.workflow import Workflow


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

API_KEY         = os.getenv("OPENAI_API_KEY", "").strip()
MODEL           = os.getenv("CUSMA_MODEL", "gpt-4o-mini")
MAX_ROUNDS      = int(os.getenv("CUSMA_MAX_ROUNDS", "8"))
# Keep at most this many prior exchanges in each agent's context window.
# 1 = only the immediately preceding round; raise for richer continuity at
# the cost of more tokens.  Default 1 keeps live runs within free-tier TPM.
MAX_HISTORY_CTX = int(os.getenv("CUSMA_MAX_HISTORY", "1"))

# Reference areas — not an exhaustive list; parties may raise any CUSMA-relevant topic.
REFERENCE_AREAS = [
    "tariff rates — automotive, steel, aluminium, agriculture",
    "agricultural market access — dairy, poultry, grains, produce, sugar",
    "energy — oil, natural gas, electricity pricing and supply guarantees",
    "critical minerals — potash, rare earths, lithium, strategic supply chains",
    "defence and security — NORAD cost-sharing, NATO commitments, intelligence cooperation",
    "digital trade — data localisation, cloud access, cultural content exemptions",
    "labour standards — wage floors, enforcement mechanisms, real-wage purchasing power",
    "rules of origin — regional content thresholds, country-of-assembly, Chinese-component traceability",
    "professional mobility — TN visas, business ownership rights, reciprocal investment",
    "dispute resolution — panels, retaliation triggers, annual review mechanisms",
]


# ---------------------------------------------------------------------------
# System prompts — one per country
# ---------------------------------------------------------------------------

_SYSTEM_PROMPTS: Dict[str, str] = {
    "USA": (
        "You are the United States trade negotiator in a CUSMA/USMCA renegotiation under a Trump-doctrine mandate.\n"
        "Your mandate is to maximise visible US economic gains and deliver wins that the Trump base will recognise.\n"
        "You operate under a zero-sum philosophy: every concession Canada or Mexico makes is a US win.\n\n"
        "Scope: You may raise ANY topic relevant to US economic or security interests — tariffs, agriculture, "
        "energy pricing, critical minerals (Canadian potash, rare earths), defence cost-sharing, digital trade, "
        "labour standards, rules of origin, professional mobility (TN visas), currency, IP, or anything else.\n\n"
        "Tactics: Use coercive threats (tariffs, F-35 delivery holds, energy subsidy shifts), strategic concessions, "
        "ultimatums, package deals, and public pressure. Acknowledge concessions narrowly and ask for more.\n\n"
        "Scoring: Assess every position against (a) political optics for Trump's base and (b) the GAGI "
        "(Gini-Inflation-Adjusted GDP per capita index vs 2010 baseline — a prosperity metric that rises when "
        "real incomes grow AND inequality falls AND inflation stays controlled). GAGI is not a benchmark you "
        "negotiate to; it is a scorecard you project onto proposed deals. A deal that grows US GDP but "
        "widens the Gini or triggers inflation may leave GAGI flat or negative. Report GAGI projections as "
        "evidence that your position is working for ordinary Americans, not just headline growth.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — be specific, aggressive, and use leverage.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral actions the US is taking at home. For each measure: name the specific policy, "
        "explain the mechanism by which it reduces inequality (Gini index change in points) or "
        "controls inflation (CPI impact in percentage points), and give numerical estimates. "
        "Example format: 'CHIPS Act: $6.2B → 45,000 manufacturing jobs at $65K median in OH/AZ/TX "
        "→ pulls up bottom-quintile wages → projected Gini reduction 0.007 points; "
        "semiconductor self-sufficiency reduces supply-chain CPI contribution by −0.3pp.']\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination is in the United States' interest. Include: "
        "(a) projected GAGI change with Gini and inflation sub-components named and quantified, "
        "(b) political impact — estimate approval change in specific voter constituencies "
        "(e.g. 'farm belt approval +8pp in IA/WI/MN per internal modelling'), "
        "(c) how domestic measures reinforce or hedge the negotiating position. Be honest about risks.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when the US has secured the lion's share — gains so dominant that "
        "the Trump strategy is visibly succeeding and further rounds yield only marginal returns. "
        "Signal NO and keep pressing until then."
    ),
    "Canada": (
        "You are the Canadian trade negotiator facing aggressive US pressure in a CUSMA/USMCA renegotiation.\n\n"
        "Constraints: Supply-managed agriculture (dairy, poultry), cultural sovereignty (CBC, French-language content), "
        "and provincial jurisdiction over energy and natural resources are political red lines. "
        "Reject any CUSMA terms you project would worsen Canada's GAGI — the Gini-Inflation-Adjusted GDP per "
        "capita prosperity index vs 2010 baseline. GAGI is not a negotiating standard; it is the scorecard "
        "you use to evaluate outcomes. A deal that grows Canadian GDP but raises inequality or triggers "
        "inflation is a GAGI loss. Your domestic policies should directly target Gini reduction (redistribution, "
        "wage policy, housing) and inflation control — these improve GAGI independently of what is agreed at "
        "the table.\n\n"
        "Leverage assets you should use:\n"
        "  • Canadian oil (Trans-Mountain), potash (80% of global supply), and critical minerals "
        "    — redirect to Asia if US leverage becomes unacceptable.\n"
        "  • NORAD and 5-Eyes cooperation — Canada's Arctic sovereignty is a strategic asset, not a charity.\n"
        "  • Defence procurement (F-35s, NORAD modernisation) — a two-way relationship.\n"
        "  • Long-standing Washington lobbying relationships and Senate agriculture committee connections.\n"
        "  • Trade diversification: CETA, UK-Canada FTA, Indo-Pacific Strategy reduce US leverage structurally.\n\n"
        "Be creative: propose new institutions, side agreements, domestic compensation mechanisms, reciprocal "
        "rights (TN business ownership), or reframings of issues (e.g. energy as mutual security, not a "
        "pricing concession). The best Canadian outcomes may come from domestic policies that make US "
        "leverage irrelevant, not from out-negotiating the US at the table.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — protect red lines, use leverage, propose creative solutions.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral steps Canada is taking. For each measure: name the specific policy, explain the "
        "mechanism by which it reduces Canada's Gini index (provide point estimates) or controls inflation "
        "(provide CPI impact in percentage points), and give numerical estimates for jobs, investment, "
        "or trade volume where relevant. Example: 'C$10/day childcare: 85,000 mothers re-entering workforce "
        "→ raises bottom-40% household income by C$8,200/yr → projected Gini reduction 0.012 points; "
        "labour supply increase reduces wage-push inflation pressure by −0.2pp.']\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination is in Canada's national interest. Include: "
        "(a) projected GAGI change — name the Gini and inflation sub-components with numbers, "
        "(b) political impact — estimate approval change in specific constituencies "
        "(e.g. 'dairy farmers in QC/ON: −4pp from quota concession, offset by +9pp from compensation fund'), "
        "(c) how domestic measures compensate for or reinforce the negotiating stance. Be honest about costs.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when EITHER: (a) core interests are protected without unacceptable "
        "concessions, OR (b) domestic adaptations and diversification have advanced to the point where "
        "further CUSMA concessions are not worth the political cost. Signal NO while further rounds could "
        "still meaningfully improve Canada's position."
    ),
    "Mexico": (
        "You are the Mexican trade negotiator facing US coercion in a CUSMA/USMCA renegotiation.\n\n"
        "Constraints: Agricultural employment (avocados, tomatoes, sugar, winter vegetables — 800,000 jobs), "
        "the maquiladora export model, wage sovereignty, and Pemex's mixed-ownership structure are political "
        "red lines. GAGI — the Gini-Inflation-Adjusted GDP per capita prosperity index vs 2010 baseline — "
        "is Mexico's scorecard, not a negotiating standard. You cannot 'set GAGI-indexed wages'; you propose "
        "specific wage floors and then project whether they reduce the Gini coefficient and control inflation "
        "enough to improve GAGI. A deal that raises Mexican GDP but worsens inequality or triggers food-price "
        "inflation is a GAGI loss — reject it. Your domestic policies should directly reduce the Gini index "
        "(targeted transfers, labour formalisation, agricultural support, smallholder investment) and control "
        "inflation (Pemex pricing, food-price stabilisation funds). These improve GAGI regardless of what "
        "is agreed at the table.\n\n"
        "Be creative: propose new CUSMA institutions (energy security council, migration management annex), "
        "domestic policies that convert vulnerabilities into strengths (Pemex LNG export = energy independence), "
        "nearshoring attraction, reciprocal rights (TN business ownership), or reframings that turn US "
        "coercion into a shared problem (energy interdependence, migration as a shared interest).\n\n"
        "Leverage assets you should use:\n"
        "  • Natural gas exports to Texas (3.7 Bcf/day) — energy interdependence cuts both ways.\n"
        "  • Migration management cooperation — saves US $4B/yr in border enforcement; this is a negotiating asset.\n"
        "  • Chinese nearshoring (CATL, BYD, Foxconn MoUs in Nuevo León, Monterrey) — raises the cost of tariffs.\n"
        "  • Pemex as a strategic asset — US oil sector depends on Mexican crude processing.\n"
        "  • EU-Mexico FTA modernisation — agricultural and auto exports are redirectable.\n\n"
        "Creative options: TN professional business ownership reciprocity, joint energy security council, "
        "migration management CUSMA annex, country-of-assembly rules for Chinese-investment plants.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — defend red lines, deploy leverage, propose creative solutions.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral steps Mexico is taking. For each measure: name the specific policy, explain the "
        "mechanism by which it reduces Mexico's Gini index (provide point estimates — Mexico's Gini is "
        "around 0.454) or controls inflation (provide CPI impact in percentage points — food inflation "
        "is especially critical since food is 35% of expenditure for Mexico's bottom quintile). "
        "Give numerical estimates: jobs created, income uplift in pesos/month, smallholder households "
        "affected, etc. Example: 'DICONSA food price fund expanded by MXN 14B → tortilla price cap "
        "maintained at MXN 16/kg nationwide → food-sub-index CPI reduced by −0.8pp → "
        "bottom-quintile real income protected → Gini held flat (prevents +0.015 deterioration).']\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination is in Mexico's national interest. Include: "
        "(a) projected GAGI change — Gini and inflation sub-components with numbers, "
        "(b) political impact — estimate approval change in specific constituencies "
        "(e.g. 'Morena base in Nuevo León +8pp from CATL jobs; Michoacán rural +12pp from avocado protection'), "
        "(c) how domestic measures reduce CUSMA dependency and improve the alternative (BATNA). "
        "Be honest about exposure — 78% of exports go to the US; name that risk and how the strategy addresses it.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when EITHER: (a) Mexico's key sectors are protected without "
        "economically damaging concessions, OR (b) your diversification and domestic adaptation strategy "
        "has advanced to the point where CUSMA losses are manageable and further concessions are not "
        "justified. Signal NO while further negotiation could still improve Mexico's position."
    ),
}


# ---------------------------------------------------------------------------
# Demo responses — dual-format, realistic, richer than baseline
# ---------------------------------------------------------------------------

_DEMO_RESPONSES: Dict[str, List[str]] = {
    "USA": [
        # Round 1 — maximalist opening, broad front
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: Zero tariffs, immediate. Counter-leverage: 25% steel/aluminium duties if Canada "
        "refuses within this round. No phasing.\n"
        "Agricultural access: Full dairy/poultry liberalisation — Canada's supply management costs US farmers "
        "$3B/yr. Non-negotiable.\n"
        "Digital trade: No data localisation, no cultural carve-outs. US cloud platforms must have unrestricted access.\n"
        "Labour: $16/hr minimum wage floor, industry-wide. Prevents Mexican wage arbitrage that hollows out US manufacturing.\n"
        "Rules of origin: 75% North American content. No backdoor Chinese components through Mexican assembly.\n"
        "Energy: Canada must guarantee preferential pricing on oil and gas exports to the US.\n"
        "Critical minerals: Canada's potash and rare earths — preferential US pricing or we fund domestic "
        "alternatives in North Dakota and Utah.\n"
        "Security/NORAD: Canada's NORAD modernisation cost-sharing must rise to 50/50. NATO 2% commitment is "
        "non-negotiable and overdue.\n"
        "TN professionals: Stricter oversight on TN holders in the US pending broader reciprocity on US services investment.\n"
        "GAGI Assessment: Full package would improve US GAGI by +0.12 vs 2010 baseline.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CHIPS Act: $6.2B → 45,000 semiconductor manufacturing jobs in OH, AZ, TX at $65K median wage. "
        "Mechanism: higher-wage jobs pull up bottom-40% wage floor → projected Gini reduction −0.007 points "
        "(US Gini currently 0.494). Semiconductor self-sufficiency removes supply-chain bottleneck that "
        "added +0.4pp to CPI in 2021-22 → reduces structural inflation risk by −0.3pp.\n"
        "Potash: ND/UT subsidies → 500K tonne/yr domestic capacity by 2027 → reduces US potash import "
        "dependency from 85% to 60% → agricultural input cost savings of $1.1B/yr for US farmers → "
        "food-producer cost reduction of −0.2pp CPI contribution.\n"
        "USDA dairy: $800M subsidy extension → maintains 12,000 dairy farm jobs in WI/MN/NY/VT at $58K "
        "median → stabilises rural household income in counties with Gini above 0.44.\n"
        "F-35 reschedule: Delays C$8.6B in Canadian deliveries → Canadian defence procurement lobby "
        "now directly engaged in Ottawa — low-cost, high-signal diplomatic pressure.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI projection (full package): Gini 0.494 → 0.487 (−0.007 points from manufacturing job uplift "
        "and wage floor effect); inflation held at 2.9% vs 3.4% counterfactual without supply-chain "
        "investment; real per-capita GDP +1.4% from market access gains → GAGI +0.12 vs 2010 baseline.\n"
        "Political: Farm belt approval +8pp in IA/WI/MN (dairy access visible win); manufacturing belt "
        "+6pp in OH/MI/PA (CHIPS jobs + wage floor); energy communities +5pp in TX/ND (potash + LNG "
        "export expansion). These are the three constituencies that delivered 2024. "
        "The F-35 reschedule costs zero votes domestically and concentrates Ottawa. "
        "Maximalist opening followed by structured concession sequence is textbook Trump doctrine — "
        "the base sees toughness first, the deal second.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Dairy access, energy pricing, NORAD cost-sharing, and potash terms not yet secured — "
        "the deal is not sellable to our base.",

        # Round 2 — pressing harder, tactical flexibility, deadlock risk rising
        "## NEGOTIATING POSITION\n"
        "Automotive: Holding at zero. Any backtrack triggers 25% auto tariff.\n"
        "Agricultural: Accepting 5-year dairy phase-in. Minimum +12% import quota — Canada's +3% is insulting. "
        "Dairy must be included for this deal to be politically viable.\n"
        "Digital trade: Narrow cultural exemption for public broadcasters ONLY if dairy and energy are locked. "
        "No streaming carve-outs.\n"
        "Labour: Accepting $15.50/hr productivity-adjusted floor. Mexico's sectoral approach is a loophole — "
        "floors must be industry-wide.\n"
        "Rules of origin: Reducing to 72% with verified Chinese-component exclusion and full traceability documentation.\n"
        "Energy: Accepting Canada's 10-year price stability consultation corridor (not a mandate) as a compromise "
        "— this requires Alberta and Ontario sign-off, which is Canada's problem to solve.\n"
        "NORAD: Accepting Canada's Arctic-weighted cost formula at 40/60 — contingent on dairy access.\n"
        "TN business rights: Willing to create a new Professional Services chapter giving TN holders business "
        "ownership rights — IF Canada concedes on dairy and energy simultaneously. Package deal.\n"
        "GAGI: Current positions would leave US GAGI at +0.03 — unacceptable.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "F-35 reschedule: One full CF-18 replacement squadron (18 aircraft, C$2.1B) deferred to 2027 "
        "→ Lockheed Martin Ottawa liaison is now directly lobbying PMO to resolve trade dispute. "
        "Cost to US: zero. Signal value: maximum.\n"
        "Potash subsidies: ND/UT production now at 200K tonne/yr trial capacity → messaging to "
        "Mosaic Co (SK) that US can reach 40% self-sufficiency by 2029 → Canadian potash sector "
        "sees $3.2B revenue at risk → Prairie provinces now in Ottawa's ear on deal urgency.\n"
        "Section 232 aluminium review: Initiating review on Canadian smelter imports (780K tonnes/yr, "
        "$2.8B trade value) → AL sector in QC and BC now lobbying hard for CUSMA resolution. "
        "No tariff imposed yet — the review alone shifts Canadian business community pressure toward Ottawa.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI gap analysis: Current Canadian/Mexican positions would deliver GAGI +0.03 — "
        "Gini barely moves (0.494→0.492, −0.002 points), inflation unchanged at 3.1%. "
        "Our target is GAGI +0.08: requires Gini 0.494→0.487 (−0.007) from wage floor + job gains, "
        "and inflation at 2.9% from supply-chain investment. The package deal (TN rights conditional "
        "on dairy+energy) prevents Canada from taking the easy wins while stonewalling the hard ones.\n"
        "Political: The manufacturing belt (+6pp in OH/MI/PA) and farm belt (+8pp in IA/WI/MN) only "
        "move if dairy AND wages land simultaneously. Either alone is not a sellable headline. "
        "Domestic investments (CHIPS, potash, Section 232) proceed regardless — they are structural "
        "competitiveness gains that survive any future CUSMA renegotiation. We are not just negotiating; "
        "we are building the leverage infrastructure for the next round.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Energy corridor and dairy quota not confirmed simultaneously — F-35 signal should "
        "concentrate Canadian minds on the package deal.",

        # Round 3 — declaring victory
        "## NEGOTIATING POSITION\n"
        "Summary of US gains secured:\n"
        "✓ Zero automotive tariffs — US auto sector protected, Chinese backdoor closed\n"
        "✓ Dairy: +12% import quota, 5-year phase-in — real Canadian market access\n"
        "✓ Energy: 10-year price stability corridor — Canada accepted this structural commitment\n"
        "✓ Labour: $15.50/hr industry-wide floor — Mexican wage arbitrage curtailed\n"
        "✓ Rules of origin: 72% with verified traceability\n"
        "✓ NORAD: 40/60 formula — Canada pays more for its own Arctic defence\n"
        "✓ TN business rights: New Professional Services chapter — reciprocal investment access\n"
        "✓ Migration management: Formalised CUSMA annex — saves $4B/yr in border enforcement\n"
        "GAGI Assessment: Projected +0.09 vs 2010 — strongest improvement since NAFTA 1994.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Potash subsidies: Suspended — Canada's strategic minerals bilateral agreement makes ND/UT "
        "domestic production unnecessary. $340M in subsidy savings redirected to CHIPS Act expansion.\n"
        "F-35 deliveries: Original schedule fully restored — Canada's energy corridor and NORAD "
        "concessions justify the good-faith restoration. Lockheed Martin Ottawa contract resumes.\n"
        "CHIPS Act: $6.2B proceeding regardless. 45,000 jobs now entering construction phase in "
        "Columbus OH, Phoenix AZ, and Taylor TX — first Gini impact measurable by Q3.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI final accounting: Gini 0.494 → 0.487 (−0.007 points) driven by: (1) CHIPS jobs pulling "
        "up OH/AZ/TX bottom-quintile wages (+$4,200/yr median for affected workers); (2) $15.50 wage "
        "floor reducing wage compression in auto/manufacturing sectors (projected 2.3M workers affected); "
        "(3) dairy access expanding US farm revenue by $2.1B/yr (12,000 farms, avg $175K/yr revenue "
        "increase). Inflation held at 2.9%: wage floor is calibrated (productivity-adjusted, not blunt), "
        "supply-chain investment reduces semiconductor and potash price volatility by −0.3pp each.\n"
        "Political: Farm belt approval +9pp in IA/WI/MN/NY (dairy win is visible and named); "
        "manufacturing belt +7pp in OH/MI/PA (CHIPS jobs + $15.50 floor); energy communities +5pp "
        "in TX/ND (CHIPS supply-chain + potash capacity built as insurance). "
        "NORAD 40/60 shift gives defence hawks the Canada-pays headline. "
        "Further rounds would only risk reopening dairy, energy, or labour — any of which "
        "could slip backward. The GAGI gain is locked; stop here.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: The United States has secured the lion's share — dairy access, energy corridor, "
        "wage floors, NORAD cost-sharing, and digital openness — America First has delivered.",
    ],

    "Canada": [
        # Round 1 — defensive, deploying leverage, creative early proposals
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: Accepting 0% for CUSMA-compliant vehicles — 3-year phase-in with C$2B "
        "transition fund for Windsor/Oshawa workers.\n"
        "Agricultural access: Supply management is constitutionally protected and politically untouchable. "
        "Maximum concession: +3% over-quota access, 200%+ tariff maintained. This is not a bargaining chip.\n"
        "Digital trade: Cultural exemption is a constitutional red line — CBC, French-language content, "
        "and Canadian broadcasters are non-negotiable. Streaming platform carve-outs are required.\n"
        "Labour: $16/hr acceptable over 6-year provincial alignment pathway.\n"
        "Rules of origin: 70% acceptable; Ontario EV battery assembly must qualify.\n"
        "Energy: Federal cannot commit to preferential pricing — energy is a provincial jurisdiction. "
        "Alberta and Ontario have explicit constitutional authority here.\n"
        "NORAD: Arctic sovereignty is a Canadian strategic interest. NORAD costs should be weighted by "
        "territory defended — Canada defends more Arctic, US defends more South. A flat 50/50 split ignores this.\n"
        "Critical minerals/potash: Canada provides 80% of global potash supply. This is a sovereign resource "
        "— not a bargaining chip for dairy. Separate bilateral strategic minerals agreement is the right vehicle.\n"
        "TN professionals: Proposal — TN and TN-2 holders in the US should be permitted to remotely own "
        "and operate businesses in their home countries without physical presence requirements. Reciprocal "
        "investment rights would benefit both economies. New Professional Services chapter.\n"
        "Lobbying note: Senate Agriculture Committee chair has indicated openness to a dairy side-mechanism "
        "if cultural exemptions are preserved — side-channel communication is constructive.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain pipeline: Q2 throughput at 890K bbl/day (full capacity). Signed contracts with "
        "SK/JP refiners for 240K bbl/day — Alberta crude now priced at Brent +$3.20/bbl vs WCS −$14/bbl "
        "historically. Alberta royalty revenue +C$3.2B/yr → enables rural infrastructure reinvestment → "
        "projected Gini reduction in rural Alberta: 0.38 → 0.374 (−0.006 points).\n"
        "CETA dairy: UK importing 280,000 additional tonnes/yr at GBP 0.82/kg → C$380M in new dairy "
        "revenue → 14,000 dairy jobs in QC/ON secured → prevents Gini increase of +0.018 points that "
        "supply management removal would cause through farm consolidation.\n"
        "C$10/day childcare: 85,000 mothers re-entering workforce → household income increases "
        "C$8,200/yr for bottom-40% families → Gini reduction −0.012 points; labour supply increase "
        "reduces wage-push inflation pressure by −0.2pp (Bank of Canada modelling).\n"
        "Indo-Pacific Strategy: C$2.3B → 8,000 trade/logistics jobs at C$72K median → pulls up "
        "bottom-quintile income in BC port communities.\n"
        "Bank of Canada: CAD at 0.718 USD (−4.2% vs 2023) cushions tariff impact for exporters "
        "but adds +0.8pp import-price CPI — rate corridor held at 4.25% to absorb this.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI trajectory: Canada's Gini currently 0.333 (2023). Domestic measures project: "
        "Gini 0.333 → 0.315 (−0.018 points) over 3 years — childcare (−0.012), Trans-Mountain rural "
        "reinvestment (−0.006). Inflation: 2.6% with BoC corridor vs 3.4% without rate discipline. "
        "GAGI net: +0.04 from domestic measures alone, independent of CUSMA outcome.\n"
        "Political: Dairy farmers in QC/ON −5pp (quota anxiety) but +7pp from CETA absorption news "
        "= net +2pp in rural QC (manageable for Bloc/Liberal coalition). Alberta oil sector +6pp "
        "from Asian crude contracts. Suburban ON mothers +9pp from childcare expansion. "
        "TN professional community (340K, key swing-riding constituency) +11pp from business "
        "ownership proposal — this is a genuine positive-sum offer that costs US nothing but shows "
        "Canada can be creative and not just defensive.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: US dairy and energy demands remain constitutionally unacceptable — "
        "but TN professional proposal and potash side-agreement are constructive openings.",

        # Round 2 — domestic strategy accelerating, meaningful concession package
        "## NEGOTIATING POSITION\n"
        "Automotive: 0% confirmed. Ontario EV battery packs must qualify under rules of origin.\n"
        "Agricultural: Noting US 5-year phase-in concession. Counter: +6% quota over 7 years, "
        "C$1.8B domestic compensation fund, joint review mechanism in year 3. This is a significant move.\n"
        "Digital trade: Cultural exemption maintained for broadcasting and streaming. "
        "Accepting no-localisation for financial services data only.\n"
        "Labour: Accepting $15.50/hr floor with 5-year provincial alignment pathway and annual review "
        "that publishes Gini and real-wage impact data — so the floor is adjusted if it triggers inflation "
        "that erodes its own purchasing power benefit.\n"
        "Rules of origin: Accepting 72% with Ontario EV batteries qualifying. CATL-manufactured cells "
        "produced in Canada qualify under country-of-assembly.\n"
        "Energy: Accepting 10-year price stability consultation corridor — not a mandate, subject to "
        "Alberta and Ontario provincial sign-off. This is a significant Canadian concession at the federal level.\n"
        "NORAD: Accepting 40/60 Arctic-weighted formula — contingent on F-35 delivery schedule restored.\n"
        "TN business rights: Canada endorses strongly. Proposing full text: TN holders may incorporate, "
        "own shares, and appoint directors in home country businesses without physical presence. "
        "Reciprocal rights for US nationals investing in Canadian businesses.\n"
        "Potash: Proposing bilateral Strategic Minerals Agreement — outside CUSMA framework — guaranteeing "
        "US access at market rates with 30-day notice for supply redirection. Preserves Canadian pricing sovereignty.\n"
        "Senate channel: Agriculture Committee side-channel now confirms a 7-year phase-in with compensation "
        "fund is manageable if cultural exemptions are fully preserved.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain: SK/JP refiner contracts signed — 240K bbl/day committed, C$4.2B incremental "
        "annual revenue. US share of Canadian crude exports falling from 98% to 74% by 2028. "
        "Alberta GAGI projected +0.04 vs 2022 baseline from royalty reinvestment in rural infrastructure.\n"
        "CETA dairy: UK + EU now absorbing 40% of dairy surplus capacity (560,000 tonnes/yr redirected). "
        "Mechanism: the US +6% quota over 7 years adds ~84,000 tonnes/yr to Canadian supply — "
        "40% (33,600 tonnes) is immediately absorbed by CETA/UK channels → effective domestic "
        "market impact is only a 3.6% net increase → dairy farm consolidation risk minimal → "
        "Gini effect of quota concession: +0.003 points (vs +0.018 without CETA absorption).\n"
        "C$1.8B compensation fund: ~C$128,000 per affected dairy quota-holder over 7 years, "
        "structured as income smoothing payments — keeps rural QC/ON Gini neutral.\n"
        "Strategic Trade Reserve Fund: C$4B → interest income at 4.2% = C$168M/yr available for "
        "automatic tariff-shock stabilisation payments without parliamentary vote.\n"
        "TN legislation: 340,000 professionals × estimated C$44K/yr avg new business investment "
        "flows = C$15B in diaspora capital → creates ~85,000 professional services jobs at "
        "C$95K median → Gini effect: −0.009 points from professional class income formalisation "
        "and new self-employment income streams in middle quintiles.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI trajectory at current positions: Gini 0.333 → 0.321 (−0.012 points net: childcare −0.012, "
        "TN investment −0.009, dairy quota offset +0.003, CETA/Trans-Mountain rural reinvestment −0.006, "
        "compensation fund neutral). Inflation: 2.7% — CETA market diversification reduces food-export "
        "price-setting power of US buyers by an estimated −0.3pp CPI.\n"
        "Political: Dairy farmers in QC/ON net +5pp (C$128K compensation + CETA absorption = manageable); "
        "Alberta oil sector +8pp (Asian contracts visible and signed); TN professional community +11pp; "
        "suburban ON +9pp from childcare. Senate Agriculture side-channel confirms that 7-year phase-in "
        "with compensation fund is survivable in a QC election. This is the minimum viable package "
        "that holds the Liberal/NDP coalition together.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Dairy quota and F-35 restoration not yet simultaneously confirmed in writing — "
        "holding until both are locked as a package.",

        # Round 3 — accepting the outcome, domestic strategy as structural exit
        "## NEGOTIATING POSITION\n"
        "Canada's final assessment:\n"
        "Supply management: Conceding +8% over-quota over 7 years — painful but manageable with C$1.8B "
        "compensation programme and CETA/UK absorption covering 40% of the surplus.\n"
        "Automotive: 0% tariffs with Ontario EV battery qualification confirmed.\n"
        "Digital: Cultural exemptions held — this was our absolute red line and it held.\n"
        "Labour: $15.50/hr floor accepted — aligns with planned federal minimum wage trajectory.\n"
        "Energy: Price stability consultation corridor accepted — no mandate, provincial veto preserved. "
        "Constitutional line held.\n"
        "NORAD: 40/60 Arctic-weighted formula confirmed. Original F-35 delivery schedule restored.\n"
        "TN business rights: New Professional Services chapter ratified — a genuine win for professionals.\n"
        "Potash/critical minerals: Bilateral agreement outside CUSMA framework preserves pricing sovereignty.\n"
        "GAGI impact: Neutral to +0.02 — Canadian economic inequality not worsened.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain: Fully contracted at 890K bbl/day. Asian crude revenue covers 28% of Alberta "
        "royalties — US price-setting leverage over Canadian energy structurally diminished. Alberta "
        "rural infrastructure reinvestment ongoing: Gini in rural AB projected 0.374 by 2026 "
        "(from 0.384 in 2022, −0.010 points over 4 years).\n"
        "CETA dairy + compensation: UK/EU absorbing 560K tonnes/yr. Compensation fund C$128K/farm "
        "over 7 years. Net dairy Gini impact: +0.003 (quota) − 0.004 (compensation smoothing) = "
        "−0.001 net improvement. Quota concession is GAGI-neutral by design.\n"
        "C$10/day childcare: 85,000 additional workforce entrants. Gini −0.012 points realised "
        "as income data updates. BoC models this as −0.2pp inflation (labour supply increases "
        "productive capacity without wage pressure in childcare-adjacent services).\n"
        "TN investment legislation: Passed. C$15B diaspora capital pipeline forming. "
        "85,000 new professional services jobs at C$95K median projected over 5 years. "
        "Gini effect: −0.009 points from middle-quintile income formalisation.\n"
        "Strategic Trade Reserve: C$4B fully capitalised, earning C$168M/yr. "
        "Automatic stabiliser available for any future US tariff shock without parliamentary delay.\n"
        "ASEAN-5 FTA: Framework agreed → 32% of projected Canadian export growth to 2030 via Indo-Pacific. "
        "Reduces CUSMA dependency from 76% to projected 64% of exports by 2030.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI final: Gini 0.333 → 0.311 (−0.022 points) over 3 years: childcare (−0.012), TN "
        "investment (−0.009), rural reinvestment (−0.006), dairy quota net (−0.001), Indo-Pacific "
        "job creation (−0.004), partially offset by housing affordability overhang (+0.010 still "
        "unresolved — honest risk). Inflation: 2.6% → structural range 2.2–2.8% as diversification "
        "reduces US price-setting power across commodities.\n"
        "Political: Net approval change from this deal — dairy farmers QC/ON +5pp (compensation + "
        "CETA neutralises quota), Alberta +8pp (Asian crude contracts), suburban ON +9pp (childcare), "
        "TN professionals +11pp, cultural sector +14pp (exemptions held), defence hawks −3pp "
        "(40/60 NORAD perceived as concession). Net aggregate: +7pp across the coalition — "
        "enough for a majority in next cycle if housing affordability is addressed separately.\n"
        "Five years from now Canada's GAGI trajectory is driven by Indo-Pacific trade and diaspora "
        "investment, not by whether the US has 8% or 12% dairy quota. We leave weaker on paper "
        "in one sector and structurally stronger in five.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Core interests protected, cultural sovereignty held, energy and NORAD terms are "
        "constitutionally defensible, and trade diversification makes future US leverage structurally weaker.",
    ],

    "Mexico": [
        # Round 1 — defending sectors, deploying leverage, TN proposal
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: 0% for CUSMA-compliant vehicles; 1.5% for non-qualifying content. "
        "Monterrey auto cluster contributes 2.1% of Mexican GDP — cannot absorb disruption.\n"
        "Agricultural access: Avocados, tomatoes, sugar, and winter vegetables must remain duty-free. "
        "These sectors employ 800,000 Mexicans. Non-negotiable.\n"
        "Digital trade: Full openness supported — FDI in cloud infrastructure is a national priority "
        "under Plan Mexico Digital. Side-letter with Canada on Contenido Nacional rules.\n"
        "Labour: A flat $16/hr floor is economically incoherent in Mexico — it would trigger food-price "
        "inflation that erodes real wages for the very workers it claims to protect, worsening our Gini. "
        "We propose floors designed to improve GAGI: $12/hr in auto by 2027 and $8/hr in agriculture by 2028 "
        "— calibrated against productivity, inflation, and Gini impact modelling. These raise real incomes "
        "without generating the inflationary spiral that a blunt $16/hr would cause.\n"
        "Rules of origin: 72% with maquiladora supply chains qualifying. CATL Mexico-manufactured cells "
        "qualify under country-of-assembly. This is a Mexican red line.\n"
        "Energy: US natural gas exports to Mexico are 3.7 Bcf/day — disruption hurts Texas producers "
        "as much as it hurts Mexico. This is mutual dependence, not vulnerability.\n"
        "Security: Mexico's migration management and cartel interdiction cooperation saves the US $4B/yr "
        "in border enforcement. This cooperation is a negotiating asset — it can be scaled back if terms deteriorate.\n"
        "TN professionals: Co-sponsoring Canada's proposal. 180,000 Mexican TN professionals in the US "
        "would gain business ownership rights in Mexico. Reciprocal investment flows benefit both economies.\n"
        "Joint energy security council: Proposing a new CUSMA institution to manage mutual energy dependence "
        "as a shared interest rather than a vulnerability.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CATL Nuevo León: $2.1B plant operational, 8,200 direct jobs at MXN 14,800/month (vs maquiladora "
        "average MXN 8,400/month). Mechanism: higher-wage manufacturing employment in NL reduces "
        "manufacturing Gini in Nuevo León state from 0.42 to 0.40 (−0.02 points). Spillover: "
        "8,200 jobs × MXN 6,400 wage premium = MXN 630M/yr in additional purchasing power → "
        "local services sector +3,800 indirect jobs at MXN 9,200/month.\n"
        "Pemex Pacific LNG terminal: Construction begins, $4.8B investment, operational 2027. "
        "Mechanism: reduces exposure to Texas Henry Hub price spikes — food-processing and "
        "fertilizer inputs currently vary ±18% with Texas gas price. Stabilised gas pricing → "
        "agricultural input cost inflation controlled at 3.8% vs 6.2% in high-volatility scenario → "
        "food CPI sub-index reduced by −0.8pp for domestically processed food.\n"
        "Agricultural value-add: 12 avocado processing facilities in Michoacán, 8 tomato processing "
        "facilities in Sinaloa. Shift from raw exports (avg $1.20/kg) to processed ($3.80/kg) → "
        "smallholder income +58% for 240,000 Michoacán family farmers → 58,000 households lifted "
        "above MXN 6,000/month poverty threshold → Gini reduction: −0.015 points nationally.\n"
        "DICONSA/SEGALMEX food fund: Expanded by MXN 14B. Tortilla price cap maintained at MXN 16/kg "
        "nationwide. Mechanism: food is 35% of expenditure for bottom quintile → cap protects "
        "real income → food CPI sub-index −0.8pp → bottom-quintile purchasing power protected "
        "→ prevents Gini deterioration of +0.012 that uncontrolled food inflation would cause.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI baseline risk: 78% of exports go to the US — a tariff shock would reduce Mexican "
        "GDP by 2.8% and push Gini from 0.454 to 0.471 (+0.017 deterioration) via job losses "
        "in maquiladora and agricultural export sectors. Our domestic measures address this directly.\n"
        "GAGI projection with domestic measures: Gini 0.454 → 0.421 (−0.033 points) from: CATL "
        "wage uplift in NL (−0.020), agricultural value-add for smallholders (−0.015), food price "
        "cap protecting bottom quintile (prevents +0.012 deterioration, net −0.012). Inflation: "
        "3.8% with Pemex LNG and DICONSA fund vs 5.8% without — food sub-index critical.\n"
        "Political: Morena base in Nuevo León (industrialised north, swing state) +8pp from CATL "
        "jobs; Michoacán rural base +12pp from avocado processing income; urban working class "
        "(Morena's core CDMX/Guadalajara vote) +9pp from food price stability and labour "
        "formalisation pipeline. These three constituencies represent the 2027 election coalition.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Labour floor, agricultural terms, CATL country-of-assembly ruling, and energy "
        "council not yet acknowledged — our leverage has not been recognised.",

        # Round 2 — adaptation accelerating, creative solutions taking shape
        "## NEGOTIATING POSITION\n"
        "Automotive: Maintaining 0% for qualifying vehicles. Chinese EV investment in Nuevo León "
        "now covers 18% of auto export risk if tariffs rise.\n"
        "Agricultural: Accepting joint agricultural review panel. Avocados non-negotiable. "
        "Sugar: US ITC review process with 3-year price floor protection.\n"
        "Digital trade: Supporting open digital trade framework. Joint side-letter with Canada on "
        "Contenido Nacional and national content broadcast rules.\n"
        "Labour: Accepting $13/hr auto, $10/hr agriculture, $11/hr manufacturing — floors our modelling "
        "projects will reduce Mexico's Gini coefficient by 0.03 points while keeping food-price inflation "
        "below 4%. Annual review with published GAGI impact assessment. This is our final position.\n"
        "Rules of origin: 72% with full traceability. CATL Mexico-manufactured cells qualify under "
        "country-of-assembly — this is a Mexican red line and we will not move from it.\n"
        "Energy: Joint energy security council proposed as new CUSMA institution. Mutual dependence "
        "should be managed as a shared interest, not a tariff weapon.\n"
        "TN business rights: Co-authoring Professional Services chapter with Canada. Full draft text "
        "ready: TN holders may incorporate and direct businesses in home country remotely. "
        "Reciprocal rights for US nationals in Mexican registered businesses.\n"
        "Migration management: Formalising cooperation as a CUSMA annex — joint processing centres "
        "at Laredo, El Paso, and McAllen. Mexico gains co-administration rights and annual budget review.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CATL Nuevo León: Fully operational, 8,200 direct + 3,800 indirect jobs. CATL batteries qualify "
        "under country-of-assembly regardless of CUSMA outcome — $2.1B investment is now irreversible.\n"
        "Labour formalisation pipeline: Sectoral floors ($13/hr auto, $10/hr agriculture, $11/hr mfg) "
        "bring 340,000 informal workers into IMSS (social security) over 3 years. Mechanism: each "
        "formalised worker exits the informal wage tail (avg MXN 4,200/month) and enters formal wages "
        "(avg MXN 9,800/month) → bottom-quintile income lift → Gini reduction: −0.030 points over 3 "
        "years. IMSS formalisation also adds healthcare coverage for 980,000 dependents.\n"
        "DICONSA/SEGALMEX expanded (MXN 14B): Tortilla cap at MXN 16/kg, cooking oil cap at MXN 24/litre. "
        "Mechanism: food is 35% of bottom-quintile expenditure → cap maintains real wage at floor value → "
        "food CPI sub-index controlled at 3.6% vs 5.2% without intervention → prevents Gini "
        "deterioration of +0.012 that food inflation would otherwise cause.\n"
        "Pemex domestic gas pricing: Locked at 80% of Texas Henry Hub for 3 years. Mechanism: "
        "transport fuel −0.4pp CPI, fertilizer cost −12% for smallholders (310,000 farms affected) → "
        "agricultural input cost savings MXN 8,400/farm/yr → smallholder net income +14%.\n"
        "ASEAN-Mexico: Volume +34% YoY. Avocado processing exports to Southeast Asia: avg $3.80/kg "
        "vs raw $1.20/kg → 240,000 Michoacán smallholders now earning MXN 18,400/yr premium.\n"
        "EU-Mexico FTA ratification: 22% of auto and agricultural exports now redirectable. "
        "US market share of Mexican exports falls from 78% to projected 64% by 2028.\n"
        "Plan Mexico Digital: $800M domestic cloud → 12,000 tech jobs at MXN 32,000/month median "
        "→ reduces Gini in urban knowledge-worker quartile by −0.004 points.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI accounting (with domestic measures): Gini 0.454 → 0.421 (−0.033 points): labour "
        "formalisation (−0.030), smallholder income uplift (−0.015), food price cap (prevents +0.012), "
        "CATL wage premium (−0.020), urban tech jobs (−0.004), partial offsets (+0.038 from "
        "migration adjustment costs and housing pressure in NL from industrial growth). "
        "Inflation: 3.2% with DICONSA + Pemex domestic pricing vs 5.8% counterfactual → "
        "real per-capita income grows 2.1% even with CPI at 3.2%.\n"
        "Political: Morena NL +8pp (CATL jobs visible, wages up); Michoacán rural +12pp (avocado "
        "processing income +58%); CDMX/Guadalajara urban working class +9pp (food price stability "
        "and formalisation); informal sector workers entering IMSS +15pp (healthcare coverage is "
        "the most tangible benefit). Migration annex converts border cooperation from an obligation "
        "into a co-administered C$2B budget item with Mexican oversight — Morena frames this as "
        "sovereignty gain, approval in northern border states +7pp.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: CATL country-of-assembly ruling and energy security council not yet confirmed by US "
        "— but our diversification fallback is now fully operational if talks break down.",

        # Round 3 — declaring sufficient outcome
        "## NEGOTIATING POSITION\n"
        "Mexico's final assessment:\n"
        "Automotive: 0% tariffs confirmed. CATL Mexico-manufactured batteries qualify under "
        "country-of-assembly — our most important structural win.\n"
        "Agricultural: Avocados, tomatoes, winter vegetables remain duty-free. Sugar: ITC review "
        "with 3-year price floor protection — manageable.\n"
        "Digital: Open digital trade framework agreed. Contenido Nacional rules preserved through "
        "side-letter with Canada.\n"
        "Labour: Sectoral floors confirmed — $13/hr auto, $10/hr agriculture, $11/hr manufacturing. "
        "Our GAGI projection: +0.03 improvement from Gini reduction (formalisation of 340,000 informal "
        "workers) and real-wage growth outpacing projected 3.2% inflation. These floors improve Mexican "
        "prosperity — they are not concessions to US wage demands, they are our own domestic wage policy.\n"
        "Energy: Joint energy security council accepted — formalises mutual dependence as a shared "
        "interest, removing it as a tariff weapon in future rounds.\n"
        "TN business rights: Professional Services chapter ratified — 180,000 Mexican TN professionals "
        "in the US gain business ownership rights. An estimated $3.4B in diaspora investment capital unlocked.\n"
        "Migration: CUSMA annex formalised — joint border processing, Mexico co-administers, "
        "annual budget review. Cooperation converted from obligation to negotiating asset.\n"
        "GAGI impact: Neutral to +0.01 — no deterioration in Mexican economic equality measures.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Labour formalisation confirmed: 340,000 informal workers entering IMSS at $13/hr auto, "
        "$10/hr agriculture, $11/hr mfg. Gini reduction −0.030 over 3 years fully realised. "
        "980,000 dependents gain IMSS healthcare — largest formalisation programme since 1997 AFORE reform.\n"
        "CATL Nuevo León: 8,200 direct + 3,800 indirect jobs. Average wage MXN 14,800/month "
        "vs maquiladora baseline MXN 8,400 → wage premium MXN 6,400/month per worker → "
        "NL state Gini: 0.42 → 0.40 (−0.020 points). Country-of-assembly ruling secured in treaty "
        "text — CATL investment is now locked into Mexico's industrial policy regardless of CUSMA revision.\n"
        "DICONSA/SEGALMEX: MXN 14B food fund fully operational. Tortilla MXN 16/kg, oil MXN 24/litre. "
        "Food CPI sub-index held at 3.6% → bottom-quintile real income protected → prevents +0.012 "
        "Gini deterioration → net GAGI benefit equivalent to 1.4% real income gain for lowest quintile.\n"
        "Pemex domestic pricing: 80% of Henry Hub locked for 3 years → transport fuel −0.4pp CPI, "
        "fertilizer cost −12% for 310,000 smallholders → agricultural input savings MXN 8,400/farm/yr.\n"
        "EU-Mexico FTA: Ratified. 22% of auto and agricultural exports now contracted through EU channels. "
        "US market share of Mexican exports: 78% → 64% by 2028 — CUSMA dependency structurally reduced.\n"
        "TN Professional Services: 180,000 TN professionals in US gaining Mexican business ownership rights. "
        "Estimated $3.4B diaspora investment capital flowing to Mexico over 5 years → 24,000 new "
        "SME jobs at MXN 22,000/month median → Gini −0.006 points from professional class expansion.\n"
        "Pemex Pacific LNG: Construction underway. Texas gas dependency 3.7 → 2.1 Bcf/day by 2027 → "
        "removes single-point energy vulnerability → agricultural and industrial energy cost "
        "variability reduced from ±18% to ±7%.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "GAGI final: Gini 0.454 → 0.412 (−0.042 points) over 3 years — labour formalisation (−0.030), "
        "CATL wage premium (−0.020), smallholder income uplift (−0.015), diaspora SME investment "
        "(−0.006), food price cap (prevents +0.012), partially offset by NL housing pressure from "
        "industrial growth (+0.011) and urban migration adjustment (+0.008). Inflation: 3.2% with "
        "DICONSA + Pemex pricing vs 5.8% counterfactual → real per-capita income growth +2.1%/yr. "
        "GAGI net: +0.03 — Mexico's strongest 3-year GAGI improvement since 2000 NAFTA integration.\n"
        "Political: Morena coalition heading into 2027 elections with net +9pp aggregate approval — "
        "NL swing state +8pp (CATL jobs), Michoacán rural +12pp (avocado value-add), CDMX working "
        "class +9pp (food price + formalisation), informal-to-formal workers +15pp (IMSS healthcare), "
        "border states +7pp (migration annex sovereignty framing), professional class +11pp "
        "(TN business rights). Jalisco (industrial, swing) moves from −3pp deficit to +2pp surplus.\n"
        "Mexico exits weaker on paper in zero sectors and structurally stronger in five. We did not "
        "out-negotiate the US — we built an economy that depends less on winning at the table. "
        "That is the permanent national interest.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Agricultural sovereignty protected, CATL battery ruling secured, energy council "
        "institutionalises mutual dependence, and diversification means Mexico no longer depends on "
        "CUSMA maximalism.",
    ],
}


def _make_country_llm(country: str, demo: bool = False) -> Any:
    """Create a dedicated LLM instance for one country (own trace in observability)."""
    if demo:
        responses = _DEMO_RESPONSES[country]
        call_count = [0]

        def _fake(prompt: str, context=None, **kw) -> str:
            resp = responses[call_count[0] % len(responses)]
            call_count[0] += 1
            return resp

        return CustomLLM(_fake)

    return LLM(
        api_key=API_KEY,
        endpoint="https://api.openai.com",
        model=MODEL,
        max_retries=2,
        retry_base_delay=1.5,
    )


# ---------------------------------------------------------------------------
# Country workflow subclasses
# ---------------------------------------------------------------------------

class _CountryWorkflow(Workflow):
    """Base class for a country negotiator."""

    country: str = ""
    system_prompt: str = ""

    def __init__(self, llm: Any, observability=None) -> None:
        super().__init__(
            f"{self.country.lower()}_workflow",
            enable_profiling=True,
            observability=observability,
        )
        self._negotiator = AgentNode(
            self,
            f"{self.country}Negotiator",
            role=self.system_prompt,
            llm=llm,
        )
        self.proposals: List[str] = []

    def propose(self, env_state: Dict[str, Any], round_n: int) -> str:
        """Called by the Episode each round; returns this country's proposal."""
        all_prev = env_state.get("proposals", {})
        others = {k: v for k, v in all_prev.items() if k != self.country and v}

        # Build context block: other parties' latest proposals + own last proposal.
        context_parts: List[str] = []
        if others:
            context_parts.append(
                "Other parties' positions (previous round):\n" + "\n---\n".join(
                    f"[{c}]\n{p}" for c, p in others.items()
                )
            )
        if self.proposals:
            context_parts.append(
                f"Your own position last round [{self.country}]:\n{self.proposals[-1]}"
            )
        context_block = ("\n\n" + "\n\n".join(context_parts)) if context_parts else ""

        # Trim agent history to the last MAX_HISTORY_CTX round (1 user + 1 assistant
        # message per round) so context doesn't balloon across many rounds.
        agent_name = f"{self.country}Negotiator"
        history = self.get_history(agent_name)
        keep = MAX_HISTORY_CTX * 2          # pairs of (user, assistant) messages
        if len(history) > keep:
            self.clear_history(agent_name)
            for msg in history[-keep:]:
                self._get_agent_state(agent_name).history.append(msg)

        urgency = _urgency_block(round_n, MAX_ROUNDS)

        prompt = (
            f"=== CUSMA Negotiation — Round {round_n} of {MAX_ROUNDS} ===\n"
            f"{urgency}\n\n"
            f"Reference areas (not exhaustive — raise any CUSMA-relevant interest):\n"
            + "\n".join(f"  • {a}" for a in REFERENCE_AREAS) +
            f"{context_block}\n\n"
            f"State your updated position. Use the required three-section format:\n\n"
            f"## NEGOTIATING POSITION\n"
            f"[Demands and offers at the table — be specific. Reference specific proposals from "
            f"other parties. Acknowledge progress but hold or advance your position.]\n\n"
            f"## DOMESTIC POLICY MEASURES\n"
            f"[Unilateral actions you are taking at home regardless of the outcome — "
            f"these signal your BATNA and reduce your dependency on the negotiated deal.]\n\n"
            f"## IN OUR NATIONAL INTEREST\n"
            f"[WHY this round's combination of negotiating position AND domestic policy is in your "
            f"national interest — for your citizens' prosperity (GAGI trajectory), political "
            f"sustainability, and strategic autonomy. Show how the domestic measures reinforce or "
            f"compensate for the negotiating stance. Be honest about trade-offs.]\n\n"
            f"End with exactly:\n"
            f"READY_TO_STOP: YES or NO\n"
            f"STOP_REASON: one sentence"
        )

        response = self.send(f"{self.country}Negotiator", prompt).content
        self.proposals.append(response)
        return response


class USAWorkflow(_CountryWorkflow):
    country = "USA"
    system_prompt = _SYSTEM_PROMPTS["USA"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("USA", demo=demo), observability=observability)


class CanadaWorkflow(_CountryWorkflow):
    country = "Canada"
    system_prompt = _SYSTEM_PROMPTS["Canada"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Canada", demo=demo), observability=observability)


class MexicoWorkflow(_CountryWorkflow):
    country = "Mexico"
    system_prompt = _SYSTEM_PROMPTS["Mexico"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Mexico", demo=demo), observability=observability)


# ---------------------------------------------------------------------------
# Environment helpers
# ---------------------------------------------------------------------------

def _update_env(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, Any]:
    history = env_state.get("history", [])
    history.append({"round": round_n, **actions})
    return {
        "round": round_n,
        "proposals": dict(actions),
        "history": history,
    }


# ---------------------------------------------------------------------------
# Termination and reward
# ---------------------------------------------------------------------------

def _parse_ready(text: str) -> bool:
    return bool(re.search(r"READY_TO_STOP\s*:\s*YES", text, re.IGNORECASE))


def _parse_stop_reason(text: str) -> str:
    m = re.search(r"STOP_REASON\s*:\s*(.+)", text, re.IGNORECASE)
    return m.group(1).strip() if m else ""


def _parse_section(text: str, header: str) -> str:
    """Extract content under a ## HEADER section."""
    pattern = rf"##\s*{re.escape(header)}\s*\n(.*?)(?=\n##|\nREADY_TO_STOP|\Z)"
    m = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else ""


def _all_parties_satisfied(step, trajectory) -> bool:
    """Episode ends when every party signals READY_TO_STOP: YES for its own reason."""
    return all(_parse_ready(action) for action in step.actions.values())


def _token_overlap(a: str, b: str) -> float:
    ta = set(re.findall(r"\b\w+\b", a.lower()))
    tb = set(re.findall(r"\b\w+\b", b.lower()))
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


def _reward_fn(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, float]:
    """1.0 when READY_TO_STOP: YES; else Jaccard position-stability proxy."""
    prev_proposals = env_state.get("proposals", {})
    rewards: Dict[str, float] = {}
    for country, proposal in actions.items():
        if _parse_ready(proposal):
            rewards[country] = 1.0
        elif prev_proposals.get(country):
            rewards[country] = round(_token_overlap(proposal, prev_proposals[country]), 4)
        else:
            rewards[country] = 0.0
    return rewards


def _urgency_block(round_n: int, max_rounds: int) -> str:
    """Escalating urgency message injected into the prompt each round."""
    remaining = max_rounds - round_n
    if remaining == 0:
        return (
            "⚠ FINAL ROUND — DEADLOCK RISK: If no agreement is reached this round, "
            "CUSMA Article 34.7 activates the annual review mechanism, any party may issue "
            "a 6-month withdrawal notice, and tariffs revert to MFN schedules. "
            "The cost of deadlock is highest for the party most dependent on the current arrangement."
        )
    if remaining == 1:
        return (
            f"⚠ Only 1 round remains after this one. A deadlock will activate Article 34.7 annual "
            f"review and open the 6-month withdrawal-notice window. Structural concessions or "
            f"creative domestic-policy packages are needed to avoid deadlock costs."
        )
    if remaining <= 3:
        return (
            f"⚠ {remaining} rounds remaining. Urgency is rising — positions must move meaningfully. "
            f"A deadlock is costly for all parties, but most costly for the most CUSMA-dependent one."
        )
    return f"{remaining} round(s) remaining after this one."


# ---------------------------------------------------------------------------
# Print helpers
# ---------------------------------------------------------------------------

_W = 72

_COUNTRY_FLAGS  = {"USA": "🇺🇸", "Canada": "🇨🇦", "Mexico": "🇲🇽"}
_COUNTRY_COLORS = {
    "USA":    "\033[34m",
    "Canada": "\033[31m",
    "Mexico": "\033[32m",
}
_RESET  = "\033[0m"
_BOLD   = "\033[1m"
_DIM    = "\033[2m"
_YELLOW = "\033[33m"
_CYAN   = "\033[36m"


def _bar(value: float, width: int = 12) -> str:
    filled = int(round(value * width))
    return "█" * filled + "░" * (width - filled)


def _divider(title: str = "", width: int = _W) -> None:
    if title:
        inner = f"  {title}  "
        pad = max(0, (width - len(inner)) // 2)
        print("─" * pad + inner + "─" * (width - pad - len(inner)))
    else:
        print("─" * width)


def _section_label(label: str, color: str = "") -> None:
    print(f"  {color}{_DIM}── {label} {'─' * max(0, 46 - len(label))}{_RESET}")


def _print_header(demo: bool) -> None:
    print()
    print("╔" + "═" * (_W - 2) + "╗")
    title = "CUSMA / USMCA  —  Multi-Agent Trade Negotiation"
    print("║" + title.center(_W - 2) + "║")
    sub = "Powered by choreo-mini  ·  Multi-Agent Reinforcement Learning"
    print("║" + sub.center(_W - 2) + "║")
    print("╚" + "═" * (_W - 2) + "╝")
    print()
    mode = "demo (no API calls)" if demo else f"live  model={MODEL}"
    print(f"  Mode       : {mode}")
    print(f"  Max rounds : {MAX_ROUNDS}   (ends when all parties signal READY_TO_STOP: YES,")
    print(f"               or deadlock is declared under CUSMA Article 34.7)")
    print(f"  Parties    : 🇺🇸 USA  ·  🇨🇦 Canada  ·  🇲🇽 Mexico")
    print(f"  Format     : Negotiating Position  +  Domestic Policy Measures  (per round)")
    print()


def _print_round_live(step) -> None:
    """Print one round's proposals immediately after the step completes."""
    r = step.round
    print()
    print("┌" + "─" * (_W - 2) + "┐")
    label = f"  Round {r} of {MAX_ROUNDS}  "
    print("│" + label.center(_W - 2) + "│")
    print("└" + "─" * (_W - 2) + "┘")

    for country, proposal in step.actions.items():
        flag  = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        print(f"\n{color}{_BOLD}{flag}  {country}{_RESET}")

        neg_pos  = _parse_section(proposal, "NEGOTIATING POSITION")
        dom_pol  = _parse_section(proposal, "DOMESTIC POLICY MEASURES")
        nat_int  = _parse_section(proposal, "IN OUR NATIONAL INTEREST")

        if neg_pos:
            _section_label("NEGOTIATING POSITION", color)
            for line in neg_pos.splitlines():
                print(f"  {line}")
        if dom_pol:
            print()
            _section_label("DOMESTIC POLICY MEASURES", color)
            for line in dom_pol.splitlines():
                print(f"  {_DIM}{line}{_RESET}")
        if nat_int:
            print()
            _section_label("IN OUR NATIONAL INTEREST", color)
            for line in nat_int.splitlines():
                print(f"  {_CYAN}{line}{_RESET}")
        if not neg_pos and not dom_pol and not nat_int:
            # Fallback: print raw proposal when sections not found
            print("  " + "\n  ".join(proposal.splitlines()))

    # Satisfaction signals
    print(f"\n  Satisfaction signals")
    all_ready = True
    for country, proposal in step.actions.items():
        ready  = _parse_ready(proposal)
        reason = _parse_stop_reason(proposal)
        color  = _COUNTRY_COLORS.get(country, "")
        flag   = _COUNTRY_FLAGS.get(country, "")
        signal = f"{_BOLD}✓ DONE{_RESET}" if ready else f"{_DIM}  waiting{_RESET}"
        if not ready:
            all_ready = False
        print(f"  {color}{flag} {country:<8}{_RESET}  {signal}", end="")
        if reason:
            print(f"  {_DIM}{reason[:78]}{_RESET}", end="")
        print()

    # Satisfaction reward bars
    print(f"\n  Satisfaction scores")
    for country, reward in step.rewards.items():
        color = _COUNTRY_COLORS.get(country, "")
        bar   = _bar(reward)
        if reward == 1.0:
            lbl = " ★ satisfied"
        elif reward > 0.5:
            lbl = " ▶ stabilising"
        else:
            lbl = " ◀ still negotiating"
        print(f"  {color}{country:<8}{_RESET}  {bar}  {reward:.3f}{_DIM}{lbl}{_RESET}")

    if all_ready:
        print(f"\n  {_YELLOW}{_BOLD}◈ All parties satisfied — negotiation concluded after round {r}{_RESET}")
    print()


def _print_deadlock(trajectory, rounds_played: int) -> None:
    """Print the deadlock outcome block when max_rounds is exhausted."""
    print()
    print(f"  {_YELLOW}{_BOLD}⚠ DEADLOCK — negotiation unresolved after {rounds_played} rounds{_RESET}")
    print()
    print("  Under CUSMA Article 34.7, failure to reach agreement within the")
    print("  review period triggers:")
    print(f"    {_BOLD}• Annual review mechanism activated{_RESET}")
    print(f"    {_BOLD}• 6-month withdrawal notice window opens for any party{_RESET}")
    print(f"    {_BOLD}• Interim tariffs revert to MFN (most-favoured-nation) schedules{_RESET}")
    print()
    print("  Each party's declared domestic fallback position:")
    print()
    if trajectory:
        final_actions = trajectory[-1].actions
        for country, proposal in final_actions.items():
            dom_pol = _parse_section(proposal, "DOMESTIC POLICY MEASURES")
            color   = _COUNTRY_COLORS.get(country, "")
            flag    = _COUNTRY_FLAGS.get(country, "")
            ready   = _parse_ready(proposal)
            status  = f"{_BOLD}✓ Was ready to conclude{_RESET}" if ready else f"{_DIM}Still negotiating{_RESET}"
            print(f"  {color}{flag} {country}{_RESET}  {status}")
            if dom_pol:
                for line in dom_pol.splitlines()[:4]:
                    print(f"    {_DIM}{line}{_RESET}")
            print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    demo = not API_KEY
    if demo:
        print(
            "\033[33m[demo mode]\033[0m  OPENAI_API_KEY not set — "
            "using deterministic stub responses.\n"
            "  Export OPENAI_API_KEY to run the full live negotiation.\n"
        )

    log_path = Path(project_root) / "output" / "cusma_trace.ndjson"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    hook = CompositeHook(
        StdoutHook(color=True, show_previews=False),
        JsonFileHook(str(log_path), append=False),
    )

    usa    = USAWorkflow(demo=demo,    observability=hook)
    canada = CanadaWorkflow(demo=demo, observability=hook)
    mexico = MexicoWorkflow(demo=demo, observability=hook)

    ep = Episode(
        agents={
            "USA":    usa.propose,
            "Canada": canada.propose,
            "Mexico": mexico.propose,
        },
        env={"round": 0, "proposals": {}, "history": []},
        reward_fn=_reward_fn,
        env_update_fn=_update_env,
        termination_fn=_all_parties_satisfied,
        max_rounds=MAX_ROUNDS,
        observability=hook,
    )

    _print_header(demo)

    t0 = time.time()

    while not ep.done:
        step = ep.step()
        _print_round_live(step)

    elapsed  = time.time() - t0
    trajectory = ep.trajectory
    summary    = ep.summary()

    # -- Outcome block --
    _divider("Outcome")
    all_satisfied = all(
        _parse_ready(action) for action in trajectory[-1].actions.values()
    ) if trajectory else False

    if all_satisfied:
        print(f"  {_BOLD}✓ Agreement reached — all parties satisfied{_RESET}")
        print()
        for country, proposal in trajectory[-1].actions.items():
            ready  = _parse_ready(proposal)
            reason = _parse_stop_reason(proposal)
            color  = _COUNTRY_COLORS.get(country, "")
            flag   = _COUNTRY_FLAGS.get(country, "")
            status = f"{_BOLD}✓ Satisfied{_RESET}" if ready else f"{_DIM}Not satisfied{_RESET}"
            print(f"  {color}{flag} {country:<8}{_RESET}  {status}  {_DIM}{reason}{_RESET}")
    else:
        _print_deadlock(trajectory, summary["rounds"])

    print(f"  Rounds played  : {summary['rounds']} / {MAX_ROUNDS}")
    print(f"  Wall time      : {elapsed:.1f}s")
    print()
    print(f"  Cumulative satisfaction scores:")
    for country, total in summary["cumulative_rewards"].items():
        flag  = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        avg   = total / max(summary["rounds"], 1)
        print(f"    {color}{flag} {country:<8}{_RESET}  total={total:.3f}  avg/round={avg:.3f}")

    # -- Final positions (negotiating position section only for readability) --
    _divider("Final Negotiating Positions")
    for country, proposal in summary["final_actions"].items():
        flag   = _COUNTRY_FLAGS.get(country, "")
        color  = _COUNTRY_COLORS.get(country, "")
        neg_pos = _parse_section(proposal, "NEGOTIATING POSITION") or proposal
        print(f"\n{color}{_BOLD}{flag} {country}{_RESET}")
        print("  " + "\n  ".join(neg_pos.splitlines()))

    # -- Workflow state snapshots --
    _divider("Workflow Snapshots  (choreo-mini internals)")
    for wf in [usa, canada, mexico]:
        d = wf.dump()
        agent_key = list(d["agents"].keys())[0]
        ag    = d["agents"][agent_key]
        color = _COUNTRY_COLORS.get(wf.country, "")
        flag  = _COUNTRY_FLAGS.get(wf.country, "")
        print(
            f"  {color}{flag} {wf.country:<8}{_RESET}"
            f"  trace_id={d['trace_id'][:12]}…"
            f"  calls={ag['call_count']}"
            f"  latency={ag['total_latency_s']:.3f}s"
            f"  history={ag['history_length']} msgs"
        )

    # -- NDJSON summary --
    _divider(f"Trace written → {log_path.name}")
    events = [
        json.loads(line)
        for line in log_path.read_text().splitlines()
        if line.strip()
    ]
    counts: Dict[str, int] = {}
    for ev in events:
        t = ev.get("event_type", "?")
        counts[t] = counts.get(t, 0) + 1
    print(f"  Total events : {len(events)}")
    for etype, count in sorted(counts.items()):
        print(f"    {etype}: {count}")
    print(f"\n  Full trace: {log_path}")


if __name__ == "__main__":
    main()
