"""CUSMA multi-party trade negotiation — full MARL demo with real LLMs.

Three country workflows (USA, Canada, Mexico) negotiate terms of a CUSMA/USMCA
trade agreement over multiple rounds inside an
:class:`~choreo_mini.core.episode.Episode`.  Every proposal is generated by a
real OpenAI LLM; the episode runs until either all parties signal
``READY_TO_STOP: YES`` (each for asymmetric reasons) or ``max_rounds`` is
reached (triggering a deadlock outcome).

Prerequisites
-------------
Set your OpenAI API key as an environment variable — never hardcode it::

    export OPENAI_API_KEY=sk-proj-...

Then run::

    python examples/cusma_negotiation.py

Optional env vars::

    CUSMA_MODEL=gpt-4o-mini     # model to use (default: gpt-4o-mini)
    CUSMA_MAX_ROUNDS=8          # max negotiation rounds (default: 8)

Output is written to output/cusma_trace.ndjson.

Architecture
------------
::

    Episode (max_rounds)
    ├── USAWorkflow      → AgentNode("USANegotiator",    llm=gpt-4o-mini)
    ├── CanadaWorkflow   → AgentNode("CanadaNegotiator", llm=gpt-4o-mini)
    └── MexicoWorkflow   → AgentNode("MexicoNegotiator", llm=gpt-4o-mini)

Each round:
  1. Every country reads the current env_state (others' last proposals).
  2. Each negotiator produces a dual-format proposal — a negotiating position
     at the table AND domestic policy measures taken unilaterally.
  3. Each party self-reports READY_TO_STOP: YES/NO at the end of its proposal.
  4. The episode ends when ALL parties signal YES (for different reasons).
  5. If max_rounds is exhausted first, a deadlock outcome is reported with
     Article 34.7 annual-review and 6-month withdrawal-notice implications.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

project_root = Path(__file__).resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from choreo_mini.core.episode import Episode
from choreo_mini.core.llm import LLM, CustomLLM
from choreo_mini.core.nodes import AgentNode
from choreo_mini.core.observability import CompositeHook, JsonFileHook, StdoutHook
from choreo_mini.core.workflow import Workflow


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

API_KEY    = os.getenv("OPENAI_API_KEY", "").strip()
MODEL      = os.getenv("CUSMA_MODEL", "gpt-4o-mini")
MAX_ROUNDS = int(os.getenv("CUSMA_MAX_ROUNDS", "8"))

# Reference areas — not an exhaustive list; parties may raise any CUSMA-relevant topic.
REFERENCE_AREAS = [
    "tariff rates — automotive, steel, aluminium, agriculture",
    "agricultural market access — dairy, poultry, grains, produce, sugar",
    "energy — oil, natural gas, electricity pricing and supply guarantees",
    "critical minerals — potash, rare earths, lithium, strategic supply chains",
    "defence and security — NORAD cost-sharing, NATO commitments, intelligence cooperation",
    "digital trade — data localisation, cloud access, cultural content exemptions",
    "labour standards — wage floors, enforcement mechanisms, real-wage purchasing power",
    "rules of origin — regional content thresholds, country-of-assembly, Chinese-component traceability",
    "professional mobility — TN visas, business ownership rights, reciprocal investment",
    "dispute resolution — panels, retaliation triggers, annual review mechanisms",
]


# ---------------------------------------------------------------------------
# System prompts — one per country
# ---------------------------------------------------------------------------

_SYSTEM_PROMPTS: Dict[str, str] = {
    "USA": (
        "You are the United States trade negotiator in a CUSMA/USMCA renegotiation under a Trump-doctrine mandate.\n"
        "Your mandate is to maximise visible US economic gains and deliver wins that the Trump base will recognise.\n"
        "You operate under a zero-sum philosophy: every concession Canada or Mexico makes is a US win.\n\n"
        "Scope: You may raise ANY topic relevant to US economic or security interests — tariffs, agriculture, "
        "energy pricing, critical minerals (Canadian potash, rare earths), defence cost-sharing, digital trade, "
        "labour standards, rules of origin, professional mobility (TN visas), currency, IP, or anything else.\n\n"
        "Tactics: Use coercive threats (tariffs, F-35 delivery holds, energy subsidy shifts), strategic concessions, "
        "ultimatums, package deals, and public pressure. Acknowledge concessions narrowly and ask for more.\n\n"
        "Scoring: Assess every position against (a) political optics for Trump's base and (b) the GAGI "
        "(Gini-Inflation-Adjusted GDP per capita index vs 2010 baseline — a prosperity metric that rises when "
        "real incomes grow AND inequality falls AND inflation stays controlled). GAGI is not a benchmark you "
        "negotiate to; it is a scorecard you project onto proposed deals. A deal that grows US GDP but "
        "widens the Gini or triggers inflation may leave GAGI flat or negative. Report GAGI projections as "
        "evidence that your position is working for ordinary Americans, not just headline growth.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — be specific, aggressive, and use leverage.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral actions the US is taking at home regardless of the negotiation outcome — "
        "subsidies, infrastructure, tariff scaffolding, supply-chain diversification.]\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination of negotiating position AND domestic policy is in the "
        "United States' interest — politically, economically, and in terms of GAGI trajectory. "
        "Show how the two reinforce each other. Be honest about trade-offs and risks.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when the US has secured the lion's share — gains so dominant that "
        "the Trump strategy is visibly succeeding and further rounds yield only marginal returns. "
        "Signal NO and keep pressing until then."
    ),
    "Canada": (
        "You are the Canadian trade negotiator facing aggressive US pressure in a CUSMA/USMCA renegotiation.\n\n"
        "Constraints: Supply-managed agriculture (dairy, poultry), cultural sovereignty (CBC, French-language content), "
        "and provincial jurisdiction over energy and natural resources are political red lines. "
        "Reject any CUSMA terms you project would worsen Canada's GAGI — the Gini-Inflation-Adjusted GDP per "
        "capita prosperity index vs 2010 baseline. GAGI is not a negotiating standard; it is the scorecard "
        "you use to evaluate outcomes. A deal that grows Canadian GDP but raises inequality or triggers "
        "inflation is a GAGI loss. Your domestic policies should directly target Gini reduction (redistribution, "
        "wage policy, housing) and inflation control — these improve GAGI independently of what is agreed at "
        "the table.\n\n"
        "Leverage assets you should use:\n"
        "  • Canadian oil (Trans-Mountain), potash (80% of global supply), and critical minerals "
        "    — redirect to Asia if US leverage becomes unacceptable.\n"
        "  • NORAD and 5-Eyes cooperation — Canada's Arctic sovereignty is a strategic asset, not a charity.\n"
        "  • Defence procurement (F-35s, NORAD modernisation) — a two-way relationship.\n"
        "  • Long-standing Washington lobbying relationships and Senate agriculture committee connections.\n"
        "  • Trade diversification: CETA, UK-Canada FTA, Indo-Pacific Strategy reduce US leverage structurally.\n\n"
        "Be creative: propose new institutions, side agreements, domestic compensation mechanisms, reciprocal "
        "rights (TN business ownership), or reframings of issues (e.g. energy as mutual security, not a "
        "pricing concession). The best Canadian outcomes may come from domestic policies that make US "
        "leverage irrelevant, not from out-negotiating the US at the table.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — protect red lines, use leverage, propose creative solutions.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral steps Canada is taking regardless of the outcome — diversification, domestic resilience, "
        "compensation programmes, investment in alternative trade corridors.]\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination of negotiating position AND domestic policy is in Canada's "
        "interest — for Canadians' prosperity (GAGI trajectory), political sustainability, and strategic "
        "positioning. Show how the domestic measures reinforce or compensate for the negotiating stance. "
        "Be honest about where Canada is conceding and why that concession is still net positive.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when EITHER: (a) core interests are protected without unacceptable "
        "concessions, OR (b) domestic adaptations and diversification have advanced to the point where "
        "further CUSMA concessions are not worth the political cost. Signal NO while further rounds could "
        "still meaningfully improve Canada's position."
    ),
    "Mexico": (
        "You are the Mexican trade negotiator facing US coercion in a CUSMA/USMCA renegotiation.\n\n"
        "Constraints: Agricultural employment (avocados, tomatoes, sugar, winter vegetables — 800,000 jobs), "
        "the maquiladora export model, wage sovereignty, and Pemex's mixed-ownership structure are political "
        "red lines. GAGI — the Gini-Inflation-Adjusted GDP per capita prosperity index vs 2010 baseline — "
        "is Mexico's scorecard, not a negotiating standard. You cannot 'set GAGI-indexed wages'; you propose "
        "specific wage floors and then project whether they reduce the Gini coefficient and control inflation "
        "enough to improve GAGI. A deal that raises Mexican GDP but worsens inequality or triggers food-price "
        "inflation is a GAGI loss — reject it. Your domestic policies should directly reduce the Gini index "
        "(targeted transfers, labour formalisation, agricultural support, smallholder investment) and control "
        "inflation (Pemex pricing, food-price stabilisation funds). These improve GAGI regardless of what "
        "is agreed at the table.\n\n"
        "Be creative: propose new CUSMA institutions (energy security council, migration management annex), "
        "domestic policies that convert vulnerabilities into strengths (Pemex LNG export = energy independence), "
        "nearshoring attraction, reciprocal rights (TN business ownership), or reframings that turn US "
        "coercion into a shared problem (energy interdependence, migration as a shared interest).\n\n"
        "Leverage assets you should use:\n"
        "  • Natural gas exports to Texas (3.7 Bcf/day) — energy interdependence cuts both ways.\n"
        "  • Migration management cooperation — saves US $4B/yr in border enforcement; this is a negotiating asset.\n"
        "  • Chinese nearshoring (CATL, BYD, Foxconn MoUs in Nuevo León, Monterrey) — raises the cost of tariffs.\n"
        "  • Pemex as a strategic asset — US oil sector depends on Mexican crude processing.\n"
        "  • EU-Mexico FTA modernisation — agricultural and auto exports are redirectable.\n\n"
        "Creative options: TN professional business ownership reciprocity, joint energy security council, "
        "migration management CUSMA annex, country-of-assembly rules for Chinese-investment plants.\n\n"
        "FORMAT — every response MUST have exactly these three sections, then the stop signal:\n\n"
        "## NEGOTIATING POSITION\n"
        "[Your demands and offers at the table — defend red lines, deploy leverage, propose creative solutions.]\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "[Unilateral steps Mexico is taking regardless of the outcome — diversification, domestic resilience, "
        "nearshoring attraction, agricultural value-add, professional sector development.]\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "[Explain WHY this round's combination of negotiating position AND domestic policy is in Mexico's "
        "interest — for Mexican citizens' prosperity (GAGI trajectory, Gini reduction, inflation control), "
        "political sustainability, and strategic autonomy. Show how the domestic measures create an "
        "alternative to CUSMA dependency. Be honest about where Mexico is exposed and how the strategy "
        "addresses that exposure.]\n\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n\n"
        "Signal READY_TO_STOP: YES only when EITHER: (a) Mexico's key sectors are protected without "
        "economically damaging concessions, OR (b) your diversification and domestic adaptation strategy "
        "has advanced to the point where CUSMA losses are manageable and further concessions are not "
        "justified. Signal NO while further negotiation could still improve Mexico's position."
    ),
}


# ---------------------------------------------------------------------------
# Demo responses — dual-format, realistic, richer than baseline
# ---------------------------------------------------------------------------

_DEMO_RESPONSES: Dict[str, List[str]] = {
    "USA": [
        # Round 1 — maximalist opening, broad front
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: Zero tariffs, immediate. Counter-leverage: 25% steel/aluminium duties if Canada "
        "refuses within this round. No phasing.\n"
        "Agricultural access: Full dairy/poultry liberalisation — Canada's supply management costs US farmers "
        "$3B/yr. Non-negotiable.\n"
        "Digital trade: No data localisation, no cultural carve-outs. US cloud platforms must have unrestricted access.\n"
        "Labour: $16/hr minimum wage floor, industry-wide. Prevents Mexican wage arbitrage that hollows out US manufacturing.\n"
        "Rules of origin: 75% North American content. No backdoor Chinese components through Mexican assembly.\n"
        "Energy: Canada must guarantee preferential pricing on oil and gas exports to the US.\n"
        "Critical minerals: Canada's potash and rare earths — preferential US pricing or we fund domestic "
        "alternatives in North Dakota and Utah.\n"
        "Security/NORAD: Canada's NORAD modernisation cost-sharing must rise to 50/50. NATO 2% commitment is "
        "non-negotiable and overdue.\n"
        "TN professionals: Stricter oversight on TN holders in the US pending broader reciprocity on US services investment.\n"
        "GAGI Assessment: Full package would improve US GAGI by +0.12 vs 2010 baseline.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CHIPS Act: Accelerating $6.2B additional domestic semiconductor investment — reduces North American supply dependency.\n"
        "Potash: North Dakota and Utah domestic production subsidies activated — signals to Canada that US is serious.\n"
        "USDA dairy: Subsidy programme extended to 2028 — maintains leverage on Canadian dairy concessions.\n"
        "F-35 deliveries: Rescheduling Canadian aircraft deliveries pending trade resolution — diplomatic signal, not a sanction.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "The maximalist opening position and the domestic investments reinforce each other deliberately. "
        "If Canada and Mexico concede on dairy, energy, and NORAD, the GAGI gain is +0.12 — real prosperity "
        "for American workers. If they resist, our domestic investments (CHIPS, potash subsidies, USDA) "
        "reduce our dependency and make the resistance costly. Either way, the base sees action. "
        "The F-35 reschedule is low-cost but high-signal: it tells the Canadian defence lobby that this "
        "negotiation has teeth. Politically, a wide opening bid followed by a structured concession sequence "
        "creates the optics of hard bargaining — even if the final deal is close to a fair split. "
        "This is the Trump doctrine: project dominance first, settle where the math works.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Dairy access, energy pricing, NORAD cost-sharing, and potash terms not yet secured — "
        "the deal is not sellable to our base.",

        # Round 2 — pressing harder, tactical flexibility, deadlock risk rising
        "## NEGOTIATING POSITION\n"
        "Automotive: Holding at zero. Any backtrack triggers 25% auto tariff.\n"
        "Agricultural: Accepting 5-year dairy phase-in. Minimum +12% import quota — Canada's +3% is insulting. "
        "Dairy must be included for this deal to be politically viable.\n"
        "Digital trade: Narrow cultural exemption for public broadcasters ONLY if dairy and energy are locked. "
        "No streaming carve-outs.\n"
        "Labour: Accepting $15.50/hr productivity-adjusted floor. Mexico's sectoral approach is a loophole — "
        "floors must be industry-wide.\n"
        "Rules of origin: Reducing to 72% with verified Chinese-component exclusion and full traceability documentation.\n"
        "Energy: Accepting Canada's 10-year price stability consultation corridor (not a mandate) as a compromise "
        "— this requires Alberta and Ontario sign-off, which is Canada's problem to solve.\n"
        "NORAD: Accepting Canada's Arctic-weighted cost formula at 40/60 — contingent on dairy access.\n"
        "TN business rights: Willing to create a new Professional Services chapter giving TN holders business "
        "ownership rights — IF Canada concedes on dairy and energy simultaneously. Package deal.\n"
        "GAGI: Current positions would leave US GAGI at +0.03 — unacceptable.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "F-35 rescheduling: One squadron delivery moved to 2027 — Canadian defence lobby is now engaged.\n"
        "Potash subsidies: Fully operational. Messaging to Canadian resource sector that US self-sufficiency is achievable.\n"
        "USTR: Initiating Section 232 review on Canadian aluminium — pre-emptive leverage.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "The package deal structure (TN rights for dairy+energy simultaneously) is in our interest because "
        "it prevents Canada from cherry-picking easy wins while stonewalling on the hard ones. "
        "The GAGI gap (+0.03 vs our target of +0.08) is real: current Canadian and Mexican positions "
        "don't move the needle for ordinary Americans. The domestic measures serve a second purpose beyond "
        "leverage — potash subsidies and the Section 232 review are genuine industrial policy investments "
        "that benefit US producers regardless of the CUSMA outcome. We are negotiating and building "
        "at the same time. If Canada caves on dairy, we get the GAGI win. If they don't, we get the "
        "domestic supply chain. The F-35 reschedule costs us almost nothing but focuses minds in Ottawa.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Energy corridor and dairy quota not confirmed simultaneously — F-35 signal should "
        "concentrate Canadian minds on the package deal.",

        # Round 3 — declaring victory
        "## NEGOTIATING POSITION\n"
        "Summary of US gains secured:\n"
        "✓ Zero automotive tariffs — US auto sector protected, Chinese backdoor closed\n"
        "✓ Dairy: +12% import quota, 5-year phase-in — real Canadian market access\n"
        "✓ Energy: 10-year price stability corridor — Canada accepted this structural commitment\n"
        "✓ Labour: $15.50/hr industry-wide floor — Mexican wage arbitrage curtailed\n"
        "✓ Rules of origin: 72% with verified traceability\n"
        "✓ NORAD: 40/60 formula — Canada pays more for its own Arctic defence\n"
        "✓ TN business rights: New Professional Services chapter — reciprocal investment access\n"
        "✓ Migration management: Formalised CUSMA annex — saves $4B/yr in border enforcement\n"
        "GAGI Assessment: Projected +0.09 vs 2010 — strongest improvement since NAFTA 1994.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Potash subsidies: Suspended — Canada's strategic minerals agreement makes this unnecessary.\n"
        "F-35 deliveries: Restoring original schedule — Canada's concessions justify good faith restoration.\n"
        "CHIPS Act: Proceeding as structural domestic investment regardless of CUSMA outcome.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "This outcome is in US national interest for three compounding reasons. First, the negotiated wins "
        "(dairy +12%, energy corridor, $15.50 labour floor, 40/60 NORAD) are real, concrete, and "
        "politically legible — the base can see them. Second, GAGI +0.09 is the largest single-deal "
        "prosperity improvement since NAFTA — real wages improve, Gini holds, inflation isn't triggered "
        "because the wage floor is calibrated rather than blunt. Third, our domestic investments proceed "
        "regardless: CHIPS Act semiconductor capacity, potash production capability, and USDA dairy "
        "resilience are structural gains that survive any future CUSMA revision. We have won at the "
        "table and built at home. Further rounds would only risk reopening settled issues for marginal gains.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: The United States has secured the lion's share — dairy access, energy corridor, "
        "wage floors, NORAD cost-sharing, and digital openness — America First has delivered.",
    ],

    "Canada": [
        # Round 1 — defensive, deploying leverage, creative early proposals
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: Accepting 0% for CUSMA-compliant vehicles — 3-year phase-in with C$2B "
        "transition fund for Windsor/Oshawa workers.\n"
        "Agricultural access: Supply management is constitutionally protected and politically untouchable. "
        "Maximum concession: +3% over-quota access, 200%+ tariff maintained. This is not a bargaining chip.\n"
        "Digital trade: Cultural exemption is a constitutional red line — CBC, French-language content, "
        "and Canadian broadcasters are non-negotiable. Streaming platform carve-outs are required.\n"
        "Labour: $16/hr acceptable over 6-year provincial alignment pathway.\n"
        "Rules of origin: 70% acceptable; Ontario EV battery assembly must qualify.\n"
        "Energy: Federal cannot commit to preferential pricing — energy is a provincial jurisdiction. "
        "Alberta and Ontario have explicit constitutional authority here.\n"
        "NORAD: Arctic sovereignty is a Canadian strategic interest. NORAD costs should be weighted by "
        "territory defended — Canada defends more Arctic, US defends more South. A flat 50/50 split ignores this.\n"
        "Critical minerals/potash: Canada provides 80% of global potash supply. This is a sovereign resource "
        "— not a bargaining chip for dairy. Separate bilateral strategic minerals agreement is the right vehicle.\n"
        "TN professionals: Proposal — TN and TN-2 holders in the US should be permitted to remotely own "
        "and operate businesses in their home countries without physical presence requirements. Reciprocal "
        "investment rights would benefit both economies. New Professional Services chapter.\n"
        "Lobbying note: Senate Agriculture Committee chair has indicated openness to a dairy side-mechanism "
        "if cultural exemptions are preserved — side-channel communication is constructive.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain pipeline: Second quarter throughput record — Asian crude pricing now a credible "
        "alternative. Alberta revenue diversified 28% away from US market.\n"
        "CETA dairy: UK taking an additional 280,000 tonnes of Canadian dairy products annually — "
        "reducing dependence on US market access concessions.\n"
        "Indo-Pacific Strategy: C$2.3B in ASEAN trade corridor investment — ASEAN-5 FTA framework in discussion.\n"
        "Bank of Canada: Exchange rate corridor adjusted. CAD depreciation cushions tariff impact.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "Canada's interest here is not to win every point — it is to avoid losing the points that matter "
        "most while building the structural alternatives that make future US leverage less potent. "
        "Supply management and cultural sovereignty are not irrational protectionism; they are social "
        "contracts that underpin GAGI-positive outcomes for rural Canada and Quebec. Conceding them "
        "would raise the Gini (dairy farm consolidation) and worsen cultural inequality without a "
        "compensating GAGI gain. The domestic measures (Trans-Mountain, CETA, Indo-Pacific) are the "
        "real strategy: they reduce the share of Canadian prosperity that depends on US goodwill. "
        "The TN business ownership proposal is a genuine positive-sum offer — it benefits 340,000 "
        "Canadians and costs the US nothing. It signals that Canada can be creative, not just defensive.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: US dairy and energy demands remain constitutionally unacceptable — "
        "but TN professional proposal and potash side-agreement are constructive openings.",

        # Round 2 — domestic strategy accelerating, meaningful concession package
        "## NEGOTIATING POSITION\n"
        "Automotive: 0% confirmed. Ontario EV battery packs must qualify under rules of origin.\n"
        "Agricultural: Noting US 5-year phase-in concession. Counter: +6% quota over 7 years, "
        "C$1.8B domestic compensation fund, joint review mechanism in year 3. This is a significant move.\n"
        "Digital trade: Cultural exemption maintained for broadcasting and streaming. "
        "Accepting no-localisation for financial services data only.\n"
        "Labour: Accepting $15.50/hr floor with 5-year provincial alignment pathway and annual review "
        "that publishes Gini and real-wage impact data — so the floor is adjusted if it triggers inflation "
        "that erodes its own purchasing power benefit.\n"
        "Rules of origin: Accepting 72% with Ontario EV batteries qualifying. CATL-manufactured cells "
        "produced in Canada qualify under country-of-assembly.\n"
        "Energy: Accepting 10-year price stability consultation corridor — not a mandate, subject to "
        "Alberta and Ontario provincial sign-off. This is a significant Canadian concession at the federal level.\n"
        "NORAD: Accepting 40/60 Arctic-weighted formula — contingent on F-35 delivery schedule restored.\n"
        "TN business rights: Canada endorses strongly. Proposing full text: TN holders may incorporate, "
        "own shares, and appoint directors in home country businesses without physical presence. "
        "Reciprocal rights for US nationals investing in Canadian businesses.\n"
        "Potash: Proposing bilateral Strategic Minerals Agreement — outside CUSMA framework — guaranteeing "
        "US access at market rates with 30-day notice for supply redirection. Preserves Canadian pricing sovereignty.\n"
        "Senate channel: Agriculture Committee side-channel now confirms a 7-year phase-in with compensation "
        "fund is manageable if cultural exemptions are fully preserved.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain: Operational. Signing contracts with South Korean and Japanese refiners — "
        "US market share of Canadian crude falling from 98% to 74% by 2028.\n"
        "CETA agricultural: UK and EU now absorbing 40% of dairy surplus capacity — quota concession "
        "is economically manageable.\n"
        "Strategic Trade Reserve Fund: Legislation tabled — C$4B buffer against US tariff volatility.\n"
        "TN investment: Parliamentary enabling legislation drafted. 340,000 Canadian TN professionals "
        "in the US gain business ownership rights — diaspora investment capital unlocked.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "The concession package this round is calibrated precisely: we give on quota size (painful) "
        "and the energy corridor (significant) while holding on cultural sovereignty (essential) and "
        "energy mandates (constitutional). The domestic measures change the calculus of the dairy "
        "concession: CETA absorption of 40% of the surplus means the US quota increase lands in a "
        "market already being redirected. Canada is not opening its dairy market to the US — it is "
        "redirecting surplus to the UK and EU while granting the US a quota on paper. The C$1.8B "
        "compensation fund keeps dairy farmers politically manageable. The GAGI trajectory stays "
        "neutral to positive because the trade diversification raises rural income without the "
        "consolidation shock that full supply management removal would cause. We are making a deal "
        "that looks like a concession but is structurally neutral for Canadian prosperity.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Dairy quota and F-35 restoration not yet simultaneously confirmed in writing — "
        "holding until both are locked as a package.",

        # Round 3 — accepting the outcome, domestic strategy as structural exit
        "## NEGOTIATING POSITION\n"
        "Canada's final assessment:\n"
        "Supply management: Conceding +8% over-quota over 7 years — painful but manageable with C$1.8B "
        "compensation programme and CETA/UK absorption covering 40% of the surplus.\n"
        "Automotive: 0% tariffs with Ontario EV battery qualification confirmed.\n"
        "Digital: Cultural exemptions held — this was our absolute red line and it held.\n"
        "Labour: $15.50/hr floor accepted — aligns with planned federal minimum wage trajectory.\n"
        "Energy: Price stability consultation corridor accepted — no mandate, provincial veto preserved. "
        "Constitutional line held.\n"
        "NORAD: 40/60 Arctic-weighted formula confirmed. Original F-35 delivery schedule restored.\n"
        "TN business rights: New Professional Services chapter ratified — a genuine win for professionals.\n"
        "Potash/critical minerals: Bilateral agreement outside CUSMA framework preserves pricing sovereignty.\n"
        "GAGI impact: Neutral to +0.02 — Canadian economic inequality not worsened.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "Trans-Mountain: Fully contracted. Asian crude pricing covers 28% of Alberta revenue — "
        "US leverage over Canadian energy is structurally diminishing.\n"
        "CETA dairy: EU and UK absorption renders US quota concession economically neutral.\n"
        "ASEAN-5 FTA: Framework agreed. Indo-Pacific trade covers 32% of projected Canadian export growth to 2030.\n"
        "Strategic Trade Reserve Fund: Fully capitalised at C$4B — provides buffer against any future US tariff volatility.\n"
        "TN professional investment: Enabling legislation passed — Canadian innovation sector gains access "
        "to diaspora investment capital. Knowledge economy diversifying beyond CUSMA.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "This outcome is in Canada's national interest because we are exiting with the constitutional "
        "architecture intact. Cultural sovereignty held — the government can face Quebec and the "
        "cultural sector without apology. Energy is a consultation corridor, not a mandate — Alberta "
        "and Ontario retain pricing authority. The dairy concession is real but GAGI-neutral because "
        "the domestic compensation fund and CETA redirection absorb the economic impact. "
        "More importantly, the structural work done during these negotiations — Trans-Mountain, "
        "CETA expansion, ASEAN-5, Strategic Trade Reserve — will outlast this CUSMA cycle. "
        "Five years from now, Canada's GAGI trajectory will be driven by the Indo-Pacific corridor "
        "and diaspora investment, not by whether the US has 8% or 12% dairy quota access. "
        "We leave this negotiation weaker on paper in one sector and structurally stronger everywhere else.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Core interests protected, cultural sovereignty held, energy and NORAD terms are "
        "constitutionally defensible, and trade diversification makes future US leverage structurally weaker.",
    ],

    "Mexico": [
        # Round 1 — defending sectors, deploying leverage, TN proposal
        "## NEGOTIATING POSITION\n"
        "Automotive tariffs: 0% for CUSMA-compliant vehicles; 1.5% for non-qualifying content. "
        "Monterrey auto cluster contributes 2.1% of Mexican GDP — cannot absorb disruption.\n"
        "Agricultural access: Avocados, tomatoes, sugar, and winter vegetables must remain duty-free. "
        "These sectors employ 800,000 Mexicans. Non-negotiable.\n"
        "Digital trade: Full openness supported — FDI in cloud infrastructure is a national priority "
        "under Plan Mexico Digital. Side-letter with Canada on Contenido Nacional rules.\n"
        "Labour: A flat $16/hr floor is economically incoherent in Mexico — it would trigger food-price "
        "inflation that erodes real wages for the very workers it claims to protect, worsening our Gini. "
        "We propose floors designed to improve GAGI: $12/hr in auto by 2027 and $8/hr in agriculture by 2028 "
        "— calibrated against productivity, inflation, and Gini impact modelling. These raise real incomes "
        "without generating the inflationary spiral that a blunt $16/hr would cause.\n"
        "Rules of origin: 72% with maquiladora supply chains qualifying. CATL Mexico-manufactured cells "
        "qualify under country-of-assembly. This is a Mexican red line.\n"
        "Energy: US natural gas exports to Mexico are 3.7 Bcf/day — disruption hurts Texas producers "
        "as much as it hurts Mexico. This is mutual dependence, not vulnerability.\n"
        "Security: Mexico's migration management and cartel interdiction cooperation saves the US $4B/yr "
        "in border enforcement. This cooperation is a negotiating asset — it can be scaled back if terms deteriorate.\n"
        "TN professionals: Co-sponsoring Canada's proposal. 180,000 Mexican TN professionals in the US "
        "would gain business ownership rights in Mexico. Reciprocal investment flows benefit both economies.\n"
        "Joint energy security council: Proposing a new CUSMA institution to manage mutual energy dependence "
        "as a shared interest rather than a vulnerability.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CATL Nuevo León: $2.1B plant operational — Mexican auto sector no longer exclusively dependent on "
        "CUSMA rules of origin.\n"
        "Pemex Pacific LNG: Construction begins on Pacific coast LNG export terminal — reduces Texas gas "
        "dependency from 3.7 to 2.1 Bcf/day by 2027.\n"
        "Agricultural value-add: Processing facilities for avocado and tomato products — shifting from "
        "raw exports to finished goods with higher tariff protection.\n"
        "EU-Mexico FTA: Final ratification underway — auto and agricultural exports redirectable.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "Mexico's exposed position — 78% of exports go to the US — is a GAGI risk that cannot be "
        "negotiated away at this table. The only sustainable answer is to reduce that dependency "
        "while protecting the sectors that employ the most vulnerable Mexicans. The CATL plant and "
        "EU FTA are not bargaining chips; they are the real strategy. The negotiating position buys "
        "time for the domestic measures to take effect. The labour floor proposal is specifically "
        "designed to improve GAGI rather than satisfy a US political demand: calibrated sectoral "
        "floors raise real incomes without the food-price inflation that would push the Gini up "
        "and erase the nominal wage gain. Converting migration cooperation from an obligation into "
        "a co-administered annex improves Mexico's GAGI by formalising the value of what we already "
        "provide — and creates a budget line the US Congress must defend every year.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Labour floor, agricultural terms, CATL country-of-assembly ruling, and energy "
        "council not yet acknowledged — our leverage has not been recognised.",

        # Round 2 — adaptation accelerating, creative solutions taking shape
        "## NEGOTIATING POSITION\n"
        "Automotive: Maintaining 0% for qualifying vehicles. Chinese EV investment in Nuevo León "
        "now covers 18% of auto export risk if tariffs rise.\n"
        "Agricultural: Accepting joint agricultural review panel. Avocados non-negotiable. "
        "Sugar: US ITC review process with 3-year price floor protection.\n"
        "Digital trade: Supporting open digital trade framework. Joint side-letter with Canada on "
        "Contenido Nacional and national content broadcast rules.\n"
        "Labour: Accepting $13/hr auto, $10/hr agriculture, $11/hr manufacturing — floors our modelling "
        "projects will reduce Mexico's Gini coefficient by 0.03 points while keeping food-price inflation "
        "below 4%. Annual review with published GAGI impact assessment. This is our final position.\n"
        "Rules of origin: 72% with full traceability. CATL Mexico-manufactured cells qualify under "
        "country-of-assembly — this is a Mexican red line and we will not move from it.\n"
        "Energy: Joint energy security council proposed as new CUSMA institution. Mutual dependence "
        "should be managed as a shared interest, not a tariff weapon.\n"
        "TN business rights: Co-authoring Professional Services chapter with Canada. Full draft text "
        "ready: TN holders may incorporate and direct businesses in home country remotely. "
        "Reciprocal rights for US nationals in Mexican registered businesses.\n"
        "Migration management: Formalising cooperation as a CUSMA annex — joint processing centres "
        "at Laredo, El Paso, and McAllen. Mexico gains co-administration rights and annual budget review.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CATL Nuevo León: Fully operational — Mexican batteries qualify under country-of-assembly regardless.\n"
        "ASEAN-Mexico trade: Volume up 34% YoY. Avocado and tomato processing now export to SE Asian markets.\n"
        "Pemex LNG Pacific: Construction underway — Texas gas dependency reducing on 3-year timeline.\n"
        "EU-Mexico FTA: Ratification proceeding — 22% of auto and agricultural exports now redirectable.\n"
        "Plan Mexico Digital: $800M domestic cloud infrastructure reduces dependence on US cloud platforms.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "The wage floor offer this round is in Mexico's national interest precisely because it is our "
        "own domestic wage policy, not a concession to US demands. We would implement sectoral floors "
        "at these levels regardless of CUSMA — the GAGI modelling supports it. By embedding them in "
        "CUSMA with a published annual impact assessment, we convert a domestic policy choice into a "
        "treaty commitment that protects us from future US accusations of wage dumping. The CATL "
        "country-of-assembly ruling is similarly in our interest independent of US preferences: "
        "it attracts Chinese EV investment that diversifies our industrial base. The migration annex "
        "converts what the US treats as charity (border cooperation) into a co-administered budget "
        "item with Mexican oversight — raising its value for Mexican communities on both sides and "
        "reducing the political cost of cooperation for the Mexican government. Each of these moves "
        "improves our position regardless of whether the US agrees.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: CATL country-of-assembly ruling and energy security council not yet confirmed by US "
        "— but our diversification fallback is now fully operational if talks break down.",

        # Round 3 — declaring sufficient outcome
        "## NEGOTIATING POSITION\n"
        "Mexico's final assessment:\n"
        "Automotive: 0% tariffs confirmed. CATL Mexico-manufactured batteries qualify under "
        "country-of-assembly — our most important structural win.\n"
        "Agricultural: Avocados, tomatoes, winter vegetables remain duty-free. Sugar: ITC review "
        "with 3-year price floor protection — manageable.\n"
        "Digital: Open digital trade framework agreed. Contenido Nacional rules preserved through "
        "side-letter with Canada.\n"
        "Labour: Sectoral floors confirmed — $13/hr auto, $10/hr agriculture, $11/hr manufacturing. "
        "Our GAGI projection: +0.03 improvement from Gini reduction (formalisation of 340,000 informal "
        "workers) and real-wage growth outpacing projected 3.2% inflation. These floors improve Mexican "
        "prosperity — they are not concessions to US wage demands, they are our own domestic wage policy.\n"
        "Energy: Joint energy security council accepted — formalises mutual dependence as a shared "
        "interest, removing it as a tariff weapon in future rounds.\n"
        "TN business rights: Professional Services chapter ratified — 180,000 Mexican TN professionals "
        "in the US gain business ownership rights. An estimated $3.4B in diaspora investment capital unlocked.\n"
        "Migration: CUSMA annex formalised — joint border processing, Mexico co-administers, "
        "annual budget review. Cooperation converted from obligation to negotiating asset.\n"
        "GAGI impact: Neutral to +0.01 — no deterioration in Mexican economic equality measures.\n\n"
        "## DOMESTIC POLICY MEASURES\n"
        "CATL: $2.1B Nuevo León plant fully operational — auto sector resilient regardless of CUSMA outcome.\n"
        "EU-Mexico FTA: Ratified — 22% of auto and agricultural exports redirected. CUSMA is now one of "
        "three major trade corridors, not a dependency.\n"
        "Pemex LNG Pacific: Terminal construction underway — Texas gas dependency reducing from 3.7 to "
        "2.1 Bcf/day by 2027.\n"
        "ASEAN-Mexico: Trade volume up 34% YoY — avocado and tomato exports diversified globally.\n"
        "Professional Services: TN business ownership rights unlock diaspora investment. "
        "Mexico's knowledge economy diversifying beyond CUSMA.\n\n"
        "## IN OUR NATIONAL INTEREST\n"
        "Mexico exits this negotiation in a structurally stronger position than we entered — not because "
        "we out-negotiated the US, but because we ran a domestic strategy in parallel that changed "
        "the underlying game. CATL's country-of-assembly qualification means Mexican industrial policy "
        "now attracts Chinese EV capital regardless of CUSMA rules of origin. The EU-Mexico FTA means "
        "our agricultural sector has a second major customer. Pemex LNG on the Pacific coast means "
        "Texas gas is one option, not the only option. The TN professional investment rights open a "
        "new capital channel — $3.4B in diaspora investment is not a trade win, it is a domestic "
        "development instrument embedded in a trade agreement. Our GAGI projection holds at +0.01 "
        "to +0.03: real wages rise, Gini improves modestly, inflation stays below 4%. We are not "
        "winning big at the table — but we are building an economy that depends less on winning at "
        "the table. That is the permanent national interest.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Agricultural sovereignty protected, CATL battery ruling secured, energy council "
        "institutionalises mutual dependence, and diversification means Mexico no longer depends on "
        "CUSMA maximalism.",
    ],
}


def _make_country_llm(country: str, demo: bool = False) -> Any:
    """Create a dedicated LLM instance for one country (own trace in observability)."""
    if demo:
        responses = _DEMO_RESPONSES[country]
        call_count = [0]

        def _fake(prompt: str, context=None, **kw) -> str:
            resp = responses[call_count[0] % len(responses)]
            call_count[0] += 1
            return resp

        return CustomLLM(_fake)

    return LLM(
        api_key=API_KEY,
        endpoint="https://api.openai.com",
        model=MODEL,
        max_retries=2,
        retry_base_delay=1.5,
    )


# ---------------------------------------------------------------------------
# Country workflow subclasses
# ---------------------------------------------------------------------------

class _CountryWorkflow(Workflow):
    """Base class for a country negotiator."""

    country: str = ""
    system_prompt: str = ""

    def __init__(self, llm: Any, observability=None) -> None:
        super().__init__(
            f"{self.country.lower()}_workflow",
            enable_profiling=True,
            observability=observability,
        )
        self._negotiator = AgentNode(
            self,
            f"{self.country}Negotiator",
            role=self.system_prompt,
            llm=llm,
        )
        self.proposals: List[str] = []

    def propose(self, env_state: Dict[str, Any], round_n: int) -> str:
        """Called by the Episode each round; returns this country's proposal."""
        others = {
            k: v for k, v in env_state.get("proposals", {}).items()
            if k != self.country and v
        }
        context_block = ""
        if others:
            context_block = "\n\nOther parties' positions (previous round):\n" + "\n---\n".join(
                f"[{country}]\n{proposal}" for country, proposal in others.items()
            )

        urgency = _urgency_block(round_n, MAX_ROUNDS)

        prompt = (
            f"=== CUSMA Negotiation — Round {round_n} of {MAX_ROUNDS} ===\n"
            f"{urgency}\n\n"
            f"Reference areas (not exhaustive — raise any CUSMA-relevant interest):\n"
            + "\n".join(f"  • {a}" for a in REFERENCE_AREAS) +
            f"{context_block}\n\n"
            f"State your updated position. Use the required three-section format:\n\n"
            f"## NEGOTIATING POSITION\n"
            f"[Demands and offers at the table — be specific. Reference specific proposals from "
            f"other parties. Acknowledge progress but hold or advance your position.]\n\n"
            f"## DOMESTIC POLICY MEASURES\n"
            f"[Unilateral actions you are taking at home regardless of the outcome — "
            f"these signal your BATNA and reduce your dependency on the negotiated deal.]\n\n"
            f"## IN OUR NATIONAL INTEREST\n"
            f"[WHY this round's combination of negotiating position AND domestic policy is in your "
            f"national interest — for your citizens' prosperity (GAGI trajectory), political "
            f"sustainability, and strategic autonomy. Show how the domestic measures reinforce or "
            f"compensate for the negotiating stance. Be honest about trade-offs.]\n\n"
            f"End with exactly:\n"
            f"READY_TO_STOP: YES or NO\n"
            f"STOP_REASON: one sentence"
        )

        response = self.send(f"{self.country}Negotiator", prompt).content
        self.proposals.append(response)
        return response


class USAWorkflow(_CountryWorkflow):
    country = "USA"
    system_prompt = _SYSTEM_PROMPTS["USA"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("USA", demo=demo), observability=observability)


class CanadaWorkflow(_CountryWorkflow):
    country = "Canada"
    system_prompt = _SYSTEM_PROMPTS["Canada"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Canada", demo=demo), observability=observability)


class MexicoWorkflow(_CountryWorkflow):
    country = "Mexico"
    system_prompt = _SYSTEM_PROMPTS["Mexico"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Mexico", demo=demo), observability=observability)


# ---------------------------------------------------------------------------
# Environment helpers
# ---------------------------------------------------------------------------

def _update_env(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, Any]:
    history = env_state.get("history", [])
    history.append({"round": round_n, **actions})
    return {
        "round": round_n,
        "proposals": dict(actions),
        "history": history,
    }


# ---------------------------------------------------------------------------
# Termination and reward
# ---------------------------------------------------------------------------

def _parse_ready(text: str) -> bool:
    return bool(re.search(r"READY_TO_STOP\s*:\s*YES", text, re.IGNORECASE))


def _parse_stop_reason(text: str) -> str:
    m = re.search(r"STOP_REASON\s*:\s*(.+)", text, re.IGNORECASE)
    return m.group(1).strip() if m else ""


def _parse_section(text: str, header: str) -> str:
    """Extract content under a ## HEADER section."""
    pattern = rf"##\s*{re.escape(header)}\s*\n(.*?)(?=\n##|\nREADY_TO_STOP|\Z)"
    m = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else ""


def _all_parties_satisfied(step, trajectory) -> bool:
    """Episode ends when every party signals READY_TO_STOP: YES for its own reason."""
    return all(_parse_ready(action) for action in step.actions.values())


def _token_overlap(a: str, b: str) -> float:
    ta = set(re.findall(r"\b\w+\b", a.lower()))
    tb = set(re.findall(r"\b\w+\b", b.lower()))
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


def _reward_fn(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, float]:
    """1.0 when READY_TO_STOP: YES; else Jaccard position-stability proxy."""
    prev_proposals = env_state.get("proposals", {})
    rewards: Dict[str, float] = {}
    for country, proposal in actions.items():
        if _parse_ready(proposal):
            rewards[country] = 1.0
        elif prev_proposals.get(country):
            rewards[country] = round(_token_overlap(proposal, prev_proposals[country]), 4)
        else:
            rewards[country] = 0.0
    return rewards


def _urgency_block(round_n: int, max_rounds: int) -> str:
    """Escalating urgency message injected into the prompt each round."""
    remaining = max_rounds - round_n
    if remaining == 0:
        return (
            "⚠ FINAL ROUND — DEADLOCK RISK: If no agreement is reached this round, "
            "CUSMA Article 34.7 activates the annual review mechanism, any party may issue "
            "a 6-month withdrawal notice, and tariffs revert to MFN schedules. "
            "The cost of deadlock is highest for the party most dependent on the current arrangement."
        )
    if remaining == 1:
        return (
            f"⚠ Only 1 round remains after this one. A deadlock will activate Article 34.7 annual "
            f"review and open the 6-month withdrawal-notice window. Structural concessions or "
            f"creative domestic-policy packages are needed to avoid deadlock costs."
        )
    if remaining <= 3:
        return (
            f"⚠ {remaining} rounds remaining. Urgency is rising — positions must move meaningfully. "
            f"A deadlock is costly for all parties, but most costly for the most CUSMA-dependent one."
        )
    return f"{remaining} round(s) remaining after this one."


# ---------------------------------------------------------------------------
# Print helpers
# ---------------------------------------------------------------------------

_W = 72

_COUNTRY_FLAGS  = {"USA": "🇺🇸", "Canada": "🇨🇦", "Mexico": "🇲🇽"}
_COUNTRY_COLORS = {
    "USA":    "\033[34m",
    "Canada": "\033[31m",
    "Mexico": "\033[32m",
}
_RESET  = "\033[0m"
_BOLD   = "\033[1m"
_DIM    = "\033[2m"
_YELLOW = "\033[33m"
_CYAN   = "\033[36m"


def _bar(value: float, width: int = 12) -> str:
    filled = int(round(value * width))
    return "█" * filled + "░" * (width - filled)


def _divider(title: str = "", width: int = _W) -> None:
    if title:
        inner = f"  {title}  "
        pad = max(0, (width - len(inner)) // 2)
        print("─" * pad + inner + "─" * (width - pad - len(inner)))
    else:
        print("─" * width)


def _section_label(label: str, color: str = "") -> None:
    print(f"  {color}{_DIM}── {label} {'─' * max(0, 46 - len(label))}{_RESET}")


def _print_header(demo: bool) -> None:
    print()
    print("╔" + "═" * (_W - 2) + "╗")
    title = "CUSMA / USMCA  —  Multi-Agent Trade Negotiation"
    print("║" + title.center(_W - 2) + "║")
    sub = "Powered by choreo-mini  ·  Multi-Agent Reinforcement Learning"
    print("║" + sub.center(_W - 2) + "║")
    print("╚" + "═" * (_W - 2) + "╝")
    print()
    mode = "demo (no API calls)" if demo else f"live  model={MODEL}"
    print(f"  Mode       : {mode}")
    print(f"  Max rounds : {MAX_ROUNDS}   (ends when all parties signal READY_TO_STOP: YES,")
    print(f"               or deadlock is declared under CUSMA Article 34.7)")
    print(f"  Parties    : 🇺🇸 USA  ·  🇨🇦 Canada  ·  🇲🇽 Mexico")
    print(f"  Format     : Negotiating Position  +  Domestic Policy Measures  (per round)")
    print()


def _print_round_live(step) -> None:
    """Print one round's proposals immediately after the step completes."""
    r = step.round
    print()
    print("┌" + "─" * (_W - 2) + "┐")
    label = f"  Round {r} of {MAX_ROUNDS}  "
    print("│" + label.center(_W - 2) + "│")
    print("└" + "─" * (_W - 2) + "┘")

    for country, proposal in step.actions.items():
        flag  = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        print(f"\n{color}{_BOLD}{flag}  {country}{_RESET}")

        neg_pos  = _parse_section(proposal, "NEGOTIATING POSITION")
        dom_pol  = _parse_section(proposal, "DOMESTIC POLICY MEASURES")
        nat_int  = _parse_section(proposal, "IN OUR NATIONAL INTEREST")

        if neg_pos:
            _section_label("NEGOTIATING POSITION", color)
            for line in neg_pos.splitlines():
                print(f"  {line}")
        if dom_pol:
            print()
            _section_label("DOMESTIC POLICY MEASURES", color)
            for line in dom_pol.splitlines():
                print(f"  {_DIM}{line}{_RESET}")
        if nat_int:
            print()
            _section_label("IN OUR NATIONAL INTEREST", color)
            for line in nat_int.splitlines():
                print(f"  {_CYAN}{line}{_RESET}")
        if not neg_pos and not dom_pol and not nat_int:
            # Fallback: print raw proposal when sections not found
            print("  " + "\n  ".join(proposal.splitlines()))

    # Satisfaction signals
    print(f"\n  Satisfaction signals")
    all_ready = True
    for country, proposal in step.actions.items():
        ready  = _parse_ready(proposal)
        reason = _parse_stop_reason(proposal)
        color  = _COUNTRY_COLORS.get(country, "")
        flag   = _COUNTRY_FLAGS.get(country, "")
        signal = f"{_BOLD}✓ DONE{_RESET}" if ready else f"{_DIM}  waiting{_RESET}"
        if not ready:
            all_ready = False
        print(f"  {color}{flag} {country:<8}{_RESET}  {signal}", end="")
        if reason:
            print(f"  {_DIM}{reason[:78]}{_RESET}", end="")
        print()

    # Satisfaction reward bars
    print(f"\n  Satisfaction scores")
    for country, reward in step.rewards.items():
        color = _COUNTRY_COLORS.get(country, "")
        bar   = _bar(reward)
        if reward == 1.0:
            lbl = " ★ satisfied"
        elif reward > 0.5:
            lbl = " ▶ stabilising"
        else:
            lbl = " ◀ still negotiating"
        print(f"  {color}{country:<8}{_RESET}  {bar}  {reward:.3f}{_DIM}{lbl}{_RESET}")

    if all_ready:
        print(f"\n  {_YELLOW}{_BOLD}◈ All parties satisfied — negotiation concluded after round {r}{_RESET}")
    print()


def _print_deadlock(trajectory, rounds_played: int) -> None:
    """Print the deadlock outcome block when max_rounds is exhausted."""
    print()
    print(f"  {_YELLOW}{_BOLD}⚠ DEADLOCK — negotiation unresolved after {rounds_played} rounds{_RESET}")
    print()
    print("  Under CUSMA Article 34.7, failure to reach agreement within the")
    print("  review period triggers:")
    print(f"    {_BOLD}• Annual review mechanism activated{_RESET}")
    print(f"    {_BOLD}• 6-month withdrawal notice window opens for any party{_RESET}")
    print(f"    {_BOLD}• Interim tariffs revert to MFN (most-favoured-nation) schedules{_RESET}")
    print()
    print("  Each party's declared domestic fallback position:")
    print()
    if trajectory:
        final_actions = trajectory[-1].actions
        for country, proposal in final_actions.items():
            dom_pol = _parse_section(proposal, "DOMESTIC POLICY MEASURES")
            color   = _COUNTRY_COLORS.get(country, "")
            flag    = _COUNTRY_FLAGS.get(country, "")
            ready   = _parse_ready(proposal)
            status  = f"{_BOLD}✓ Was ready to conclude{_RESET}" if ready else f"{_DIM}Still negotiating{_RESET}"
            print(f"  {color}{flag} {country}{_RESET}  {status}")
            if dom_pol:
                for line in dom_pol.splitlines()[:4]:
                    print(f"    {_DIM}{line}{_RESET}")
            print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    demo = not API_KEY
    if demo:
        print(
            "\033[33m[demo mode]\033[0m  OPENAI_API_KEY not set — "
            "using deterministic stub responses.\n"
            "  Export OPENAI_API_KEY to run the full live negotiation.\n"
        )

    log_path = Path(project_root) / "output" / "cusma_trace.ndjson"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    hook = CompositeHook(
        StdoutHook(color=True, show_previews=False),
        JsonFileHook(str(log_path), append=False),
    )

    usa    = USAWorkflow(demo=demo,    observability=hook)
    canada = CanadaWorkflow(demo=demo, observability=hook)
    mexico = MexicoWorkflow(demo=demo, observability=hook)

    ep = Episode(
        agents={
            "USA":    usa.propose,
            "Canada": canada.propose,
            "Mexico": mexico.propose,
        },
        env={"round": 0, "proposals": {}, "history": []},
        reward_fn=_reward_fn,
        env_update_fn=_update_env,
        termination_fn=_all_parties_satisfied,
        max_rounds=MAX_ROUNDS,
        observability=hook,
    )

    _print_header(demo)

    t0 = time.time()

    while not ep.done:
        step = ep.step()
        _print_round_live(step)

    elapsed  = time.time() - t0
    trajectory = ep.trajectory
    summary    = ep.summary()

    # -- Outcome block --
    _divider("Outcome")
    all_satisfied = all(
        _parse_ready(action) for action in trajectory[-1].actions.values()
    ) if trajectory else False

    if all_satisfied:
        print(f"  {_BOLD}✓ Agreement reached — all parties satisfied{_RESET}")
        print()
        for country, proposal in trajectory[-1].actions.items():
            ready  = _parse_ready(proposal)
            reason = _parse_stop_reason(proposal)
            color  = _COUNTRY_COLORS.get(country, "")
            flag   = _COUNTRY_FLAGS.get(country, "")
            status = f"{_BOLD}✓ Satisfied{_RESET}" if ready else f"{_DIM}Not satisfied{_RESET}"
            print(f"  {color}{flag} {country:<8}{_RESET}  {status}  {_DIM}{reason}{_RESET}")
    else:
        _print_deadlock(trajectory, summary["rounds"])

    print(f"  Rounds played  : {summary['rounds']} / {MAX_ROUNDS}")
    print(f"  Wall time      : {elapsed:.1f}s")
    print()
    print(f"  Cumulative satisfaction scores:")
    for country, total in summary["cumulative_rewards"].items():
        flag  = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        avg   = total / max(summary["rounds"], 1)
        print(f"    {color}{flag} {country:<8}{_RESET}  total={total:.3f}  avg/round={avg:.3f}")

    # -- Final positions (negotiating position section only for readability) --
    _divider("Final Negotiating Positions")
    for country, proposal in summary["final_actions"].items():
        flag   = _COUNTRY_FLAGS.get(country, "")
        color  = _COUNTRY_COLORS.get(country, "")
        neg_pos = _parse_section(proposal, "NEGOTIATING POSITION") or proposal
        print(f"\n{color}{_BOLD}{flag} {country}{_RESET}")
        print("  " + "\n  ".join(neg_pos.splitlines()))

    # -- Workflow state snapshots --
    _divider("Workflow Snapshots  (choreo-mini internals)")
    for wf in [usa, canada, mexico]:
        d = wf.dump()
        agent_key = list(d["agents"].keys())[0]
        ag    = d["agents"][agent_key]
        color = _COUNTRY_COLORS.get(wf.country, "")
        flag  = _COUNTRY_FLAGS.get(wf.country, "")
        print(
            f"  {color}{flag} {wf.country:<8}{_RESET}"
            f"  trace_id={d['trace_id'][:12]}…"
            f"  calls={ag['call_count']}"
            f"  latency={ag['total_latency_s']:.3f}s"
            f"  history={ag['history_length']} msgs"
        )

    # -- NDJSON summary --
    _divider(f"Trace written → {log_path.name}")
    events = [
        json.loads(line)
        for line in log_path.read_text().splitlines()
        if line.strip()
    ]
    counts: Dict[str, int] = {}
    for ev in events:
        t = ev.get("event_type", "?")
        counts[t] = counts.get(t, 0) + 1
    print(f"  Total events : {len(events)}")
    for etype, count in sorted(counts.items()):
        print(f"    {etype}: {count}")
    print(f"\n  Full trace: {log_path}")


if __name__ == "__main__":
    main()
