"""CUSMA multi-party trade negotiation — full MARL demo with real LLMs.

Three country workflows (USA, Canada, Mexico) negotiate terms of a simplified
CUSMA/USMCA trade agreement over multiple rounds inside an
:class:`~choreo_mini.core.episode.Episode`.  Every proposal is generated by a
real OpenAI LLM; the episode runs until either rewards stabilise (Nash
convergence proxy) or ``max_rounds`` is reached.

Prerequisites
-------------
Set your OpenAI API key as an environment variable — never hardcode it::

    export OPENAI_API_KEY=sk-proj-...

Then run::

    python examples/cusma_negotiation.py

Optional env vars::

    CUSMA_MODEL=gpt-4o-mini          # model to use (default: gpt-4o-mini)
    CUSMA_MAX_ROUNDS=6               # max negotiation rounds (default: 6)
    CUSMA_CONVERGENCE_WINDOW=3       # convergence window (default: 3)

Output is written to output/cusma_trace.ndjson.

Architecture
------------
::

    Episode (max_rounds)
    ├── USAWorkflow      → AgentNode("USANegotiator",    llm=gpt-4o-mini)
    ├── CanadaWorkflow   → AgentNode("CanadaNegotiator", llm=gpt-4o-mini)
    └── MexicoWorkflow   → AgentNode("MexicoNegotiator", llm=gpt-4o-mini)

Each round:
  1. Every country reads the current env_state (others' last proposals).
  2. Each negotiator produces a structured proposal (JSON-ish key/value block).
  3. A reward function scores convergence by measuring token overlap across
     proposals; when all three countries are within threshold the episode ends.

This example is deliberately kept to a single file so it can be shared and
run without modification.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

project_root = Path(__file__).resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from choreo_mini.core.episode import Episode
from choreo_mini.core.llm import LLM, CustomLLM
from choreo_mini.core.nodes import AgentNode
from choreo_mini.core.observability import CompositeHook, JsonFileHook, StdoutHook
from choreo_mini.core.workflow import Workflow


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

API_KEY     = os.getenv("OPENAI_API_KEY", "").strip()
MODEL       = os.getenv("CUSMA_MODEL", "gpt-4o-mini")
MAX_ROUNDS  = int(os.getenv("CUSMA_MAX_ROUNDS", "8"))

NEGOTIATION_TOPICS = [
    "automotive tariff rates (target: 0–5%)",
    "agricultural market access (dairy, poultry, grains)",
    "digital trade & data localisation rules",
    "labour standards and wage floors",
    "supply chain rules of origin (75% regional content target)",
]

# ---------------------------------------------------------------------------
# System prompts — one per country
# ---------------------------------------------------------------------------

_SYSTEM_PROMPTS: Dict[str, str] = {
    "USA": (
        "You are the United States trade negotiator in a CUSMA/USMCA renegotiation under a Trump-doctrine mandate. "
        "Your priorities are to maximize US economic interests and deliver visible wins for your political base. "
        "You operate under a zero-sum philosophy: you win at the direct expense of the other parties. "
        "You may negotiate on ANY topic relevant to CUSMA/USMCA or broader US economic interests — tariffs, "
        "supply chains, agriculture, digital trade, labour, energy, currency, IP, dispute resolution, or anything else. "
        "You are free to use any negotiation tactic: strategic concessions, coercive threats, ultimatums, package deals, "
        "side-payments, and public pressure. Acknowledge concessions from Canada and Mexico but reciprocate narrowly. "
        "For each position, consider: (a) domestic political impact on Trump's base, (b) true economic impact on "
        "ordinary Americans using the GAGI index (Gini-inflation-adjusted GDP per capita ratio vs 2010 baseline). "
        "\n\nSTOPPING CONDITION: At the end of every response you MUST include exactly these two lines:\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n"
        "Signal YES only when you believe you have secured the lion's share of the deal — when US gains are so "
        "dominant that the Trump strategy is visibly succeeding and further negotiation yields only marginal returns. "
        "Until then, signal NO and keep pressing."
    ),
    "Canada": (
        "You are the Canadian trade negotiator in a CUSMA/USMCA renegotiation facing aggressive US pressure. "
        "You are constrained by domestic political realities: protecting supply-managed agriculture, cultural sovereignty, "
        "and provincial interests are red lines. You must also protect Canada's GAGI index trajectory — do not accept "
        "terms that would materially worsen Canadian economic inequality or living standards. "
        "You may negotiate on any CUSMA-relevant topic. Beyond negotiation, you are actively exploring: "
        "(a) trade diversification to EU, UK, and Asia-Pacific partners to reduce CUSMA dependency, "
        "(b) domestic industrial policy to build supply-chain resilience, "
        "(c) constitutional or provincial policy adjustments that neutralise US leverage. "
        "\n\nSTOPPING CONDITION: At the end of every response you MUST include exactly these two lines:\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n"
        "Signal YES only when EITHER: (a) you have protected your core interests without unacceptable concessions, "
        "OR (b) you have identified domestic adaptations / trade diversification strategies that make CUSMA terms "
        "sufficiently irrelevant that further negotiation is not worth the political cost. "
        "Signal NO while you still believe further rounds could improve Canada's position."
    ),
    "Mexico": (
        "You are the Mexican trade negotiator in a CUSMA/USMCA renegotiation facing US coercion. "
        "You are constrained by domestic political realities: protecting agricultural employment (especially avocados, "
        "tomatoes, sugar), the maquiladora export model, and wage sovereignty. You use the GAGI index to assess "
        "whether any deal genuinely improves Mexican living standards — reject terms that worsen inequality even if "
        "GDP headline numbers look acceptable. "
        "You may negotiate on any CUSMA-relevant topic. In parallel you are actively developing: "
        "(a) trade relationships with China, EU, and ASEAN to reduce dependence on the US market, "
        "(b) nearshoring policies to attract non-US foreign investment, "
        "(c) domestic agricultural support programmes and value-added processing to reduce raw-export vulnerability. "
        "\n\nSTOPPING CONDITION: At the end of every response you MUST include exactly these two lines:\n"
        "READY_TO_STOP: YES or NO\n"
        "STOP_REASON: one sentence\n"
        "Signal YES only when EITHER: (a) you have protected Mexico's key sectors without economically damaging "
        "concessions, OR (b) your diversification/domestic adaptation strategy has advanced to the point where "
        "CUSMA losses are manageable and further concessions are not justified. "
        "Signal NO while further negotiation could still improve Mexico's position."
    ),
}


# ---------------------------------------------------------------------------
# LLM factory
# ---------------------------------------------------------------------------

_DEMO_RESPONSES: Dict[str, List[str]] = {
    "USA": [
        # Round 1 — opening maximalist position
        "Automotive tariffs: Demand immediate zero tariffs. Any delay signals weakness. "
        "Counter-leverage: 25% steel/aluminum duties if Canada refuses within this round.\n"
        "Agricultural access: Full dairy/poultry liberalisation — Canada's supply management "
        "is a protectionist relic costing US farmers $3B/yr. Non-negotiable.\n"
        "Digital trade: No data localisation, no cultural carve-outs. US cloud platforms must "
        "have unrestricted access to Canadian and Mexican markets.\n"
        "Labour standards: $16/hr minimum wage floor, strictly enforced. Prevents Mexican "
        "wage arbitrage that hollows out US manufacturing.\n"
        "Rules of origin: 75% North American content — tightened from USMCA 2020 levels. "
        "No backdoor Chinese components through Mexican assembly.\n"
        "Energy: Canada must guarantee preferential pricing on oil and gas exports to the US.\n"
        "GAGI Impact Assessment: These terms would improve US GAGI by an estimated +0.12 "
        "vs 2010 baseline, reversing the stagnation of the Obama/Biden years.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: We have not yet secured dairy access or energy pricing — the deal "
        "would not be sellable to our base without these wins.",

        # Round 2 — pressing harder, some tactical flexibility
        "Automotive tariffs: Holding at zero. Canada and Mexico have already conceded "
        "this in principle — any backtrack triggers immediate 25% auto tariff.\n"
        "Agricultural access: Accepting 5-year phase-in for Canadian dairy quotas "
        "but minimum +15% import quota is the floor. Canada's +5% offer is insulting.\n"
        "Digital trade: Conceding narrow cultural exemption for Canadian broadcasters "
        "ONLY if dairy and energy terms are locked. No streaming platform carve-outs.\n"
        "Labour standards: Accepting $15.50/hr productivity-adjusted floor. "
        "Mexico's sectoral proposal is a loophole — wage floors must be industry-wide.\n"
        "Rules of origin: Will reduce to 72% if Mexican auto parts include verified "
        "traceability documentation excluding Chinese-sourced components.\n"
        "Energy: Canada has not responded to energy pricing demand — this is now "
        "a blocking issue. No deal without preferential pricing guarantee.\n"
        "GAGI Assessment: Current Canadian/Mexican positions would leave US GAGI at +0.03 "
        "vs 2010 — unacceptable. We need at least +0.10 to declare victory.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Energy pricing and dairy access not yet secured; "
        "without these, Trump base will view this as a failed negotiation.",

        # Round 3 — declaring victory
        "Summary of US gains secured this negotiation:\n"
        "✓ Zero automotive tariffs — US auto sector protected\n"
        "✓ Dairy: +12% import quota with 5-year phase-in — real market access\n"
        "✓ Digital: no data localisation — US cloud platforms win\n"
        "✓ Labour: $15.50/hr industry-wide floor — Mexican wage arbitrage curtailed\n"
        "✓ Rules of origin: 72% with verified traceability — Chinese backdoor closed\n"
        "✓ Energy: Canada has agreed to price stability consultations — a foundation\n"
        "GAGI Impact: Projected +0.09 vs 2010 baseline — strongest gain since NAFTA 1994.\n"
        "Political assessment: This deal is presentable as a Trump win. "
        "Canada and Mexico have made real concessions on every major US priority. "
        "Further rounds yield diminishing marginal returns.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: The United States has secured the lion's share — dairy access, "
        "zero tariffs, wage floors, and digital openness — America First has delivered.",
    ],
    "Canada": [
        # Round 1 — defensive, protecting red lines
        "Automotive tariffs: Accepting 0% for CUSMA-compliant vehicles — 3-year phase-in "
        "with C$2B transition fund for Windsor/Oshawa workers.\n"
        "Agricultural access: Supply management is constitutionally protected and "
        "politically untouchable. Maximum concession: +3% over-quota access, 200%+ tariff maintained.\n"
        "Digital trade: Cultural exemption is a constitutional red line — CBC, "
        "Canadian broadcasters, and French-language content are non-negotiable.\n"
        "Labour standards: $16/hr acceptable over 6-year transition with provincial alignment.\n"
        "Rules of origin: 70% regional content acceptable; Ontario EV battery assembly must qualify.\n"
        "Energy: Canada will not accept preferential pricing mandates — energy is a "
        "provincial jurisdiction and cannot be committed to at the federal level.\n"
        "Diversification note: Canada is in active FTA discussions with ASEAN-5 and "
        "expanding CETA scope — US leverage is diminishing.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: US dairy and energy demands remain unacceptable; "
        "we need further rounds to narrow these gaps.",

        # Round 2 — domestic adaptation strategy emerging
        "Automotive tariffs: Agreed 0% with transition funding secured from federal budget.\n"
        "Agricultural access: GAGI modelling shows supply management removal costs 14,000 "
        "rural jobs and increases GAGI inequality by 0.08 points. "
        "Counter: +5% quota, 180% tariff, joint review mechanism in year 3.\n"
        "Digital trade: Cultural exemption maintained for broadcasting. "
        "Accepting no-localisation for financial services data only.\n"
        "Labour standards: Aligning with $15.50/hr floor, phased over 5 years, "
        "with provincial opt-in mechanism.\n"
        "Rules of origin: Accepting 72% with Canadian EV battery packs qualifying.\n"
        "Energy: Federal position unchanged. Ontario/Alberta will not accept pricing mandates.\n"
        "Domestic adaptation progress: Canada-UK trade corridor operationalised for "
        "agricultural exports. ASEAN-5 FTA framework agreed in principle. "
        "US share of Canadian exports projected to fall from 76% to 68% by 2028 "
        "under current diversification trajectory — reducing CUSMA leverage over time.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Supply management and energy terms still unresolved; "
        "however our diversification strategy is progressing and leverage is shifting.",

        # Round 3 — accepting outcome, domestic strategy as exit
        "Canada's final assessment:\n"
        "Supply management: Conceding +8% over-quota access over 7 years — painful but "
        "manageable with C$1.8B domestic compensation programme.\n"
        "Automotive: 0% tariffs with EV battery qualification confirmed.\n"
        "Digital: Cultural exemptions maintained — this was our red line and it held.\n"
        "Labour: $15.50/hr floor accepted — aligns with planned federal minimum wage path.\n"
        "Energy: No pricing mandates accepted — this was a US overreach and we held firm.\n"
        "Domestic strategy: Canada-EU agricultural redirection is now covering 40% of "
        "the dairy surplus that would enter with the new quota. GAGI impact is neutral to +0.02.\n"
        "Political assessment: Canadian government can present this as protecting core "
        "interests while demonstrating resilience. Dairy concession is manageable with "
        "the compensation fund. We are not winning big — but we are not losing big either, "
        "and our diversification pathway makes future US leverage weaker.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Core interests protected, compensation programme funds the dairy "
        "transition, and trade diversification makes further CUSMA concessions unnecessary.",
    ],
    "Mexico": [
        # Round 1 — defending agricultural and labour sovereignty
        "Automotive tariffs: 0% for CUSMA-compliant vehicles; 1.5% for non-qualifying content. "
        "Monterrey auto cluster contributes 2.1% of Mexican GDP — cannot absorb disruption.\n"
        "Agricultural access: Avocados, tomatoes, sugar, and winter vegetables must remain "
        "duty-free. These sectors employ 800,000 Mexicans. Non-negotiable.\n"
        "Digital trade: Full openness supported — FDI in cloud infrastructure is a "
        "national priority under Plan Mexico Digital.\n"
        "Labour standards: A flat $16/hr floor is economically incoherent in Mexico. "
        "GAGI-adjusted productivity benchmarks by sector are the only fair metric. "
        "Auto sector floor: $12/hr by 2027. Agricultural floor: $8/hr by 2028.\n"
        "Rules of origin: 72% with phased compliance and maquiladora supply chains qualifying.\n"
        "Diversification note: Mexico has signed MoUs with 3 Chinese EV manufacturers "
        "for nearshoring investment — reducing dependency on CUSMA auto sector.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Labour floor and agricultural terms still not acceptable; "
        "our sectoral productivity approach has not been acknowledged by the US.",

        # Round 2 — adaptation strategy taking shape
        "Automotive tariffs: Maintaining 0% for qualifying vehicles. "
        "Chinese EV investment in Nuevo León now covers 18% of auto export risk if tariffs rise.\n"
        "Agricultural access: Accepting joint agricultural review panel. Avocados non-negotiable. "
        "Sugar: accepting US ITC review process with 3-year price floor protection.\n"
        "Digital trade: Supporting open digital trade framework. Working with Canada "
        "on a joint streaming platform carve-out to preserve Contenido Nacional rules.\n"
        "Labour standards: Accepting $13/hr auto floor, $10/hr agriculture, $11/hr manufacturing "
        "— all GAGI-indexed and reviewed annually. This is our final position.\n"
        "Rules of origin: 72% with full traceability for auto parts. "
        "Battery cell sourcing: CATL (China) Mexico-manufactured cells will qualify "
        "under country-of-assembly rule — this is a Mexican red line.\n"
        "Diversification progress: ASEAN-Mexico trade volume up 34% YoY. "
        "EU-Mexico modernised FTA finalised — dairy and auto exports redirectable.\n\n"
        "READY_TO_STOP: NO\n"
        "STOP_REASON: Battery sourcing rules and agricultural floors not yet resolved; "
        "however our diversification trajectory reduces urgency to concede further.",

        # Round 3 — declaring sufficient outcome
        "Mexico's final assessment:\n"
        "Automotive: 0% tariffs confirmed. CATL Mexico-manufactured batteries qualify "
        "under country-of-assembly — this is a major win for our nearshoring strategy.\n"
        "Agricultural: Avocados, tomatoes, and winter vegetables remain duty-free. "
        "Sugar: accepted US ITC review with 3-year price floor — manageable.\n"
        "Digital: Open digital trade framework agreed. National content rules preserved "
        "through side-letter with Canada.\n"
        "Labour: Sectoral GAGI-indexed floors accepted — $13/hr auto, $10/hr agriculture. "
        "This is achievable without GAGI deterioration per our modelling.\n"
        "Rules of origin: 72% with CATL qualification secured — the most important outcome.\n"
        "Diversification outcome: EU-Mexico FTA absorbs 22% of trade risk. "
        "Chinese nearshoring provides automotive resilience. CUSMA is now one of three "
        "major trade corridors rather than a dependency.\n"
        "Political assessment: President and Congress can present this as protecting "
        "workers, farmers, and sovereignty while modernising the trade mix. "
        "Further rounds would only risk reopening settled issues.\n\n"
        "READY_TO_STOP: YES\n"
        "STOP_REASON: Agricultural sovereignty protected, CATL battery ruling secured, "
        "and trade diversification means Mexico no longer depends on CUSMA maximalism.",
    ],
}


def _make_country_llm(country: str, demo: bool = False) -> Any:
    """Create a dedicated LLM instance for one country (own trace in observability)."""
    if demo:
        responses = _DEMO_RESPONSES[country]
        call_count = [0]

        def _fake(prompt: str, context=None, **kw) -> str:
            resp = responses[call_count[0] % len(responses)]
            call_count[0] += 1
            return resp

        return CustomLLM(_fake)

    return LLM(
        api_key=API_KEY,
        endpoint="https://api.openai.com",
        model=MODEL,
        max_retries=2,
        retry_base_delay=1.5,
    )


# ---------------------------------------------------------------------------
# Country workflow subclasses
# ---------------------------------------------------------------------------

class _CountryWorkflow(Workflow):
    """Base class for a country negotiator.  Subclasses set ``country`` and
    ``system_prompt`` before calling ``super().__init__()``.
    """

    country: str = ""
    system_prompt: str = ""

    def __init__(self, llm: Any, observability=None) -> None:
        super().__init__(
            f"{self.country.lower()}_workflow",
            enable_profiling=True,
            observability=observability,
        )
        self._negotiator = AgentNode(
            self,
            f"{self.country}Negotiator",
            role=self.system_prompt,
            llm=llm,
        )
        self.proposals: List[str] = []

    def propose(self, env_state: Dict[str, Any], round_n: int) -> str:
        """Called by the Episode each round; returns this country's proposal."""
        others = {
            k: v for k, v in env_state.get("proposals", {}).items()
            if k != self.country and v
        }
        context_block = ""
        if others:
            context_block = "\n\nOther parties' positions (previous round):\n" + "\n---\n".join(
                f"[{country}]\n{proposal}" for country, proposal in others.items()
            )

        rounds_left = MAX_ROUNDS - round_n
        urgency = (
            "This is the final round — a failure to reach agreement triggers "
            "automatic tariff reversion to pre-CUSMA levels."
            if rounds_left == 0
            else f"{rounds_left} round(s) remaining after this one."
        )

        prompt = (
            f"=== CUSMA Negotiation — Round {round_n} of {MAX_ROUNDS} ===\n"
            f"{urgency}\n"
            f"Reference topics (not exhaustive — raise any CUSMA-relevant interest): "
            f"{', '.join(NEGOTIATION_TOPICS)}.\n"
            f"{context_block}\n\n"
            f"State your updated position on all relevant topics. "
            f"Acknowledge any emerging consensus and state clearly where deadlocks remain. "
            f"You may introduce new proposals, coercive measures, or domestic adaptation "
            f"strategies as strategically justified.\n\n"
            f"IMPORTANT: End your response with EXACTLY these two lines (required every round):\n"
            f"READY_TO_STOP: YES or NO\n"
            f"STOP_REASON: one sentence explaining why"
        )

        response = self.send(f"{self.country}Negotiator", prompt).content
        self.proposals.append(response)
        return response


class USAWorkflow(_CountryWorkflow):
    country = "USA"
    system_prompt = _SYSTEM_PROMPTS["USA"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("USA", demo=demo), observability=observability)


class CanadaWorkflow(_CountryWorkflow):
    country = "Canada"
    system_prompt = _SYSTEM_PROMPTS["Canada"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Canada", demo=demo), observability=observability)


class MexicoWorkflow(_CountryWorkflow):
    country = "Mexico"
    system_prompt = _SYSTEM_PROMPTS["Mexico"]

    def __init__(self, demo: bool = False, observability=None) -> None:
        super().__init__(llm=_make_country_llm("Mexico", demo=demo), observability=observability)


# ---------------------------------------------------------------------------
# Environment helpers
# ---------------------------------------------------------------------------

def _update_env(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, Any]:
    history = env_state.get("history", [])
    history.append({"round": round_n, **actions})
    return {
        "round": round_n,
        "proposals": dict(actions),
        "history": history,
    }


# ---------------------------------------------------------------------------
# Satisfaction parsing — the asymmetric termination signal
# ---------------------------------------------------------------------------

def _parse_ready(text: str) -> bool:
    """Return True when the proposal contains 'READY_TO_STOP: YES'."""
    return bool(re.search(r"READY_TO_STOP\s*:\s*YES", text, re.IGNORECASE))


def _parse_stop_reason(text: str) -> str:
    """Extract the STOP_REASON sentence from a proposal."""
    m = re.search(r"STOP_REASON\s*:\s*(.+)", text, re.IGNORECASE)
    return m.group(1).strip() if m else ""


def _all_parties_satisfied(step, trajectory) -> bool:
    """Episode ends when every party signals READY_TO_STOP: YES.

    Each country stops for its own reason:
    - USA: achieved lion's share — Trump strategy vindicated
    - Canada/Mexico: core interests protected OR domestic adaptations
      make further CUSMA concessions strategically unnecessary
    """
    return all(_parse_ready(action) for action in step.actions.values())


def _token_overlap(a: str, b: str) -> float:
    """Jaccard similarity of word-token sets."""
    ta = set(re.findall(r"\b\w+\b", a.lower()))
    tb = set(re.findall(r"\b\w+\b", b.lower()))
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


def _reward_fn(
    env_state: Dict[str, Any],
    actions: Dict[str, str],
    round_n: int,
) -> Dict[str, float]:
    """Per-party satisfaction reward.

    - 1.0 when READY_TO_STOP: YES (party is satisfied on its own terms)
    - Otherwise: Jaccard overlap with previous-round proposals measures
      whether the party's position is stabilising (proxy for progress).
      Starts at 0.0 in round 1 (no prior round to compare against).
    """
    prev_proposals = env_state.get("proposals", {})
    rewards: Dict[str, float] = {}
    for country, proposal in actions.items():
        if _parse_ready(proposal):
            rewards[country] = 1.0
        elif prev_proposals.get(country):
            rewards[country] = round(
                _token_overlap(proposal, prev_proposals[country]), 4
            )
        else:
            rewards[country] = 0.0
    return rewards


# ---------------------------------------------------------------------------
# Print helpers
# ---------------------------------------------------------------------------

_W = 72   # terminal width for dividers

_COUNTRY_FLAGS = {"USA": "🇺🇸", "Canada": "🇨🇦", "Mexico": "🇲🇽"}
_COUNTRY_COLORS = {
    "USA":    "\033[34m",    # blue
    "Canada": "\033[31m",    # red
    "Mexico": "\033[32m",    # green
}
_RESET = "\033[0m"
_BOLD  = "\033[1m"
_DIM   = "\033[2m"
_YELLOW = "\033[33m"
_CYAN  = "\033[36m"


def _bar(value: float, width: int = 12) -> str:
    filled = int(round(value * width))
    return "█" * filled + "░" * (width - filled)


def _divider(title: str = "", width: int = _W) -> None:
    if title:
        inner = f"  {title}  "
        pad = max(0, (width - len(inner)) // 2)
        print("─" * pad + inner + "─" * (width - pad - len(inner)))
    else:
        print("─" * width)


def _print_header(demo: bool) -> None:
    print()
    print("╔" + "═" * (_W - 2) + "╗")
    title = "CUSMA / USMCA  —  Multi-Agent Trade Negotiation"
    print("║" + title.center(_W - 2) + "║")
    sub = "Powered by choreo-mini  ·  Multi-Agent Reinforcement Learning"
    print("║" + sub.center(_W - 2) + "║")
    print("╚" + "═" * (_W - 2) + "╝")
    print()
    mode = f"demo (no API calls)" if demo else f"live  model={MODEL}"
    print(f"  Mode       : {mode}")
    print(f"  Max rounds : {MAX_ROUNDS}   (ends when all parties signal READY_TO_STOP: YES)")
    print(f"  Parties    : 🇺🇸 USA  ·  🇨🇦 Canada  ·  🇲🇽 Mexico")
    print(f"  Topics     :")
    for t in NEGOTIATION_TOPICS:
        print(f"    • {t}")
    print()


def _print_round_live(step) -> None:
    """Print one round's proposals immediately after the step completes."""
    r = step.round
    print()
    print("┌" + "─" * (_W - 2) + "┐")
    label = f"  Round {r} of {MAX_ROUNDS}  "
    print("│" + label.center(_W - 2) + "│")
    print("└" + "─" * (_W - 2) + "┘")

    for country, proposal in step.actions.items():
        flag = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        header = f"{color}{_BOLD}{flag}  {country}{_RESET}"
        print(f"\n{header}")
        print("  " + "\n  ".join(proposal.splitlines()))

    # Convergence reward bars
    print(f"\n  {'Convergence scores':}")
    # Satisfaction signals — the asymmetric termination condition
    print(f"\n  {'Satisfaction signals':}")
    all_ready = True
    for country, proposal in step.actions.items():
        ready = _parse_ready(proposal)
        reason = _parse_stop_reason(proposal)
        color = _COUNTRY_COLORS.get(country, "")
        flag = _COUNTRY_FLAGS.get(country, "")
        if ready:
            signal = f"{_BOLD}✓ DONE{_RESET}"
        else:
            signal = f"{_DIM}  waiting{_RESET}"
            all_ready = False
        print(f"  {color}{flag} {country:<8}{_RESET}  {signal}", end="")
        if reason:
            print(f"  {_DIM}{reason[:80]}{_RESET}", end="")
        print()

    # Convergence/satisfaction reward bars
    print(f"\n  {'Satisfaction scores':}")
    for country, reward in step.rewards.items():
        color = _COUNTRY_COLORS.get(country, "")
        bar = _bar(reward)
        label = " ★ satisfied" if reward == 1.0 else (" ▶ stabilising" if reward > 0.5 else " ◀ still negotiating")
        print(f"  {color}{country:<8}{_RESET}  {bar}  {reward:.3f}{_DIM}{label}{_RESET}")

    if all_ready:
        print(f"\n  {_YELLOW}{_BOLD}◈ All parties satisfied — negotiation concluded after round {r}{_RESET}")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    demo = not API_KEY
    if demo:
        print(
            "\033[33m[demo mode]\033[0m  OPENAI_API_KEY not set — "
            "using deterministic stub responses.\n"
            "  Export OPENAI_API_KEY to run the full live negotiation.\n"
        )

    log_path = Path(project_root) / "output" / "cusma_trace.ndjson"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    # Framework event stream goes to NDJSON only during negotiation rounds;
    # proposals are printed in full by _print_round_live().
    # StdoutHook is included so tick marks (→ ←) show timing during API calls.
    hook = CompositeHook(
        StdoutHook(color=True, show_previews=False),
        JsonFileHook(str(log_path), append=False),
    )

    usa    = USAWorkflow(demo=demo,    observability=hook)
    canada = CanadaWorkflow(demo=demo, observability=hook)
    mexico = MexicoWorkflow(demo=demo, observability=hook)

    ep = Episode(
        agents={
            "USA":    usa.propose,
            "Canada": canada.propose,
            "Mexico": mexico.propose,
        },
        env={"round": 0, "proposals": {}, "history": []},
        reward_fn=_reward_fn,
        env_update_fn=_update_env,
        termination_fn=_all_parties_satisfied,
        max_rounds=MAX_ROUNDS,
        observability=hook,
    )

    _print_header(demo)

    t0 = time.time()

    # Step manually so each round's proposals print live as they complete.
    while not ep.done:
        step = ep.step()
        _print_round_live(step)

    elapsed = time.time() - t0
    trajectory = ep.trajectory
    summary = ep.summary()

    # -- Outcome --
    _divider("Outcome")
    all_satisfied = summary["done"] and ep.round < MAX_ROUNDS
    verdict = (
        "✓ All parties satisfied — negotiation concluded"
        if all_satisfied
        else "✗ Max rounds reached — negotiation unresolved"
    )
    print(f"  {_BOLD}{verdict}{_RESET}")

    # Print per-party stop reasons from the final round
    if trajectory:
        final_actions = trajectory[-1].actions
        print()
        for country, proposal in final_actions.items():
            ready = _parse_ready(proposal)
            reason = _parse_stop_reason(proposal)
            color = _COUNTRY_COLORS.get(country, "")
            flag  = _COUNTRY_FLAGS.get(country, "")
            status = f"{_BOLD}✓ Satisfied{_RESET}" if ready else f"{_DIM}Not satisfied{_RESET}"
            print(f"  {color}{flag} {country:<8}{_RESET}  {status}  {_DIM}{reason}{_RESET}")
    print(f"  Rounds played  : {summary['rounds']} / {MAX_ROUNDS}")
    print(f"  Wall time      : {elapsed:.1f}s")
    print()
    print(f"  Cumulative convergence scores:")
    for country, total in summary["cumulative_rewards"].items():
        flag = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        avg = total / max(summary["rounds"], 1)
        print(f"    {color}{flag} {country:<8}{_RESET}  total={total:.3f}  avg/round={avg:.3f}")

    # -- Final position summary --
    _divider("Final Positions")
    for country, proposal in summary["final_actions"].items():
        flag = _COUNTRY_FLAGS.get(country, "")
        color = _COUNTRY_COLORS.get(country, "")
        print(f"\n{color}{_BOLD}{flag} {country}{_RESET}")
        print("  " + "\n  ".join(proposal.splitlines()))

    # -- Workflow state snapshots --
    _divider("Workflow Snapshots  (choreo-mini internals)")
    for wf in [usa, canada, mexico]:
        d = wf.dump()
        agent_key = list(d["agents"].keys())[0]
        ag = d["agents"][agent_key]
        color = _COUNTRY_COLORS.get(wf.country, "")
        flag  = _COUNTRY_FLAGS.get(wf.country, "")
        print(
            f"  {color}{flag} {wf.country:<8}{_RESET}"
            f"  trace_id={d['trace_id'][:12]}…"
            f"  calls={ag['call_count']}"
            f"  latency={ag['total_latency_s']:.3f}s"
            f"  history={ag['history_length']} msgs"
        )

    # -- NDJSON summary --
    _divider(f"Trace written → {log_path.name}")
    events = [
        json.loads(line)
        for line in log_path.read_text().splitlines()
        if line.strip()
    ]
    counts: Dict[str, int] = {}
    for ev in events:
        t = ev.get("event_type", "?")
        counts[t] = counts.get(t, 0) + 1
    print(f"  Total events : {len(events)}")
    for etype, count in sorted(counts.items()):
        print(f"    {etype}: {count}")
    print(f"\n  Full trace: {log_path}")


if __name__ == "__main__":
    main()
